BUILD.bazel
hack/update-bazel.sh

Automanaging the `package-srcs` was causing kazel and gazelle to fight; see #5 
Also removed redundant subroutine from script; `//hack:bootstrap-testinfra` doesn't exist anymore.

Fix update-bazel test

---

images/push.sh

A script is needed to automate pushing TestGrid images; bazel won't authenticate by simply running `//images:push` in a container.

Add push script for TestGrid

---

cmd/summarizer/summary/summarizer_service.pb.go
hack/BUILD.bazel
pb/response/types.pb.go

Using importmap to get the correct import paths when importing protos into other protos.
/assign @fejta

Correctly map protos for .pb.go files.

---

OWNERS

Considering the entire repository is testgrid, this label is redundant and should be removed.
Fixes #31

Remove "area/testgrid" label

---

.bazelrc

Tested `bazel build //...` and `bazel test //...` both remotely and locally, using Bazel v1.1.0
Removing old build-ci settings since GCP/oss-test-infra Prow doesn't use RBE, and even if it did, the configuration should sit with the Prow instance and not here.
Removing `--host_force_python` since there's no python code in this repository
Also removing `--incompatible_disable_deprecated_attr_params` since we don't seem to be using deprecated params either.
/assign @fejta 
Addresses #38

Fixup .bazelrc

---

.bazelrc

Addressing previous comments from #40 
The print-workspace-status info is still here because that hack script is present and maintained by this repository to push images of Testgrid components. See [`//images:push'](https://github.com/GoogleCloudPlatform/testgrid/blob/master/images/BUILD.bazel)
The rest of the suggestions have been taken.
/assign @fejta

Also fixing .bazelrc

---

WORKSPACE

Required to run `//images:push` due to dependencies using python
Without this, `//images:push` generates the following error (with bazel 1.1.0):
```
----------------
Traceback (most recent call last):
File "/usr/local/google/home/slchase/.cache/bazel/_bazel_slchase/0cf923e311637c9c17c1bb47ed49455a/execroot/com_github_googlecloudplatform_testgrid/bazel-out/k8-fastbuild/bin/images/push.runfiles/containerregistry/tools/fast_pusher_.py", line 29, in <module>
from containerregistry.client import docker_creds
File "/usr/local/google/home/slchase/.cache/bazel/_bazel_slchase/0cf923e311637c9c17c1bb47ed49455a/execroot/com_github_googlecloudplatform_testgrid/bazel-out/k8-fastbuild/bin/images/push.runfiles/containerregistry/client/__init__.py", line 23, in <module>
from containerregistry.client …
```

Update bazel rules in Workspace

---

cmd/summarizer/BUILD.bazel
cmd/summarizer/main.go
cmd/summarizer/main_test.go
cmd/updater/main.go
go.mod
go.sum
pb/state/state.pb.go
pb/state/state.proto
repos.bzl

* Download the config proto
* For each dashboard create a summary for each tab
* For each tab
- Download the state proto
- Filter out irrelevant rows
- Find the latest run, noting if this is stale (also last update to state proto)
- Extract any active alerts
- Find the last result with only green tests
- Decide the overall tab state:
* stale if results are old
* failing if there are active alerts
* passing if all recent results are healthy
* flaky if there are some failures but no alerts
* unknown if there are not any results yet
TODO:
* Many more unit tests (let me know if you want logic to come with tests or added later)
* Failing/passing alert timestamps (external proto doesn't yet define these fields)
* Support for functionality that isn't yet being used by testgrid.k8s.io
* …

Create state based summarizer

---

BUILD.bazel
cmd/summarizer/BUILD.bazel
cmd/summarizer/main.go
cmd/summarizer/main_test.go
cmd/updater/BUILD.bazel
cmd/updater/main.go
cmd/updater/main_test.go
internal/result/BUILD.bazel
internal/result/results.go

Also make summarizer set pass/fail time.
Encapsulate result logic into an internal package (so both update and summarizer can use it).

Make updater configure alerts.

---

.bazelrc
cluster/BUILD.bazel
cluster/summarizer_deployment.yaml
cmd/summarizer/BUILD.bazel
cmd/summarizer/main.go
cmd/updater/BUILD.bazel
cmd/updater/main.go
def.bzl
images/BUILD.bazel

Also:
* Add a -wait flag to summarizer and updater, which makes them run forever.
* Rename make_image to go_image
* Build all targets in CI during bazel test //...

Create summarizer deployment.

---

cluster/BUILD.bazel
cluster/summarizer_deployment.yaml
cluster/updater_deployment.yaml
cmd/updater/main.go
images/push.sh

* Continue disallowing writing
* Fix-up deployments to include a selector and use correct image path
* Do not overwrite namespace
* Set platform when building images to deploy

Allow reading from k8s-testgrid

---

cluster/summarizer_deployment.yaml
cluster/updater_deployment.yaml
cmd/summarizer/main.go
cmd/updater/BUILD.bazel
cmd/updater/main.go
cmd/updater/main_test.go
util/gcs/read.go

* Use its own bucket rather than a subdir
* Support running continuously if `--wait` is positive
* Update all dashboards even if one fails
* Switch updater to use logrus
* Switch updater to use the configured number of days of results rather than 7
* Advance compressed index on running cells.
* Sort builds from the presubmit directory correctly.
Do you want to break this up?

Improve updater, summarizer, gcs reader

---

cluster/summarizer_deployment.yaml
cluster/updater_deployment.yaml
cmd/summarizer/main.go
cmd/updater/main.go
util/gcs/gcs.go

Otherwise values may be stale for an hour (causing the summary to be stale for up to two hours).
Fixes #64

Do not cache state, summary values.

---

cmd/updater/BUILD.bazel
cmd/updater/main.go
metadata/job.go
metadata/job_test.go

Match the way python currently finds these values.
Support more deprecated fields.
Set both the current way we read them and the way we want to read them.
Unit test this behavior
Fixes #63 
ref https://github.com/kubernetes/test-infra/issues/15434

Encapsulate how to get/set version in metadata package.

---

cmd/updater/main.go
util/gcs/read.go

GCS no longer returns `link` in addition to `x-goog-meta-link`, so use the latter.

Read from correct metadata link

---

cluster/updater_deployment.yaml
cmd/updater/main.go
util/gcs/read.go

* Remove context from gcs.Build, instead require caller to pass one in.
* Ensure updater closes all channels
* Timeout group update, make both and build timeout configurable by flag.
* Fix a potential race where multiple workers encounter an error and try to write to the error channel
* Simplify how we get started and finished
* Simplify how we cancel reading builds
* Add a --debug flag, drop intra-group logging to debug
* Add a periodic progress log about update
* Use x-goog-meta-link instead of link (server no longer returns the latter)

Simplify gcs and updater concurrency

---

images/push.sh

ref https://github.com/GoogleCloudPlatform/oss-test-infra/issues/202
`GOOGLE_APPLICATION_CREDENTIALS` is no longer set when using workload identity, it happens automatically.
So always run `gcloud auth configure-docker` which is a noop if its already done.
ref https://github.com/GoogleCloudPlatform/oss-test-infra/pull/219

Always configure docker

---

cluster/deploy.sh

Ensures context exists, optionally activates service account and has some coloring.
See https://github.com/kubernetes/test-infra/blob/master/prow/deploy.sh
ref #78

Add deploy script

---

config/config.go
config/config_test.go
config/yamlcfg/yaml2proto_test.go

Also adds more useful, structured errors.
ref #98

Validate referenced entities exist in config.

---

BUILD.bazel
cluster/canary/BUILD.bazel
cluster/canary/namespace.yaml
cluster/canary/summarizer.yaml
cluster/canary/updater.yaml
cluster/deploy.sh
cluster/prod/BUILD.bazel
cluster/prod/namespace.yaml
cluster/prod/summarizer.yaml
cluster/prod/updater.yaml
cluster/summarizer_serviceaccount.yaml
cluster/updater_serviceaccount.yaml

Deploy to testgrid-canary namespace.
Create summarizier.yaml, updater.yaml, namespace.yaml to manage resources for those apps.
Separte into cluster/prod and cluster/canary dirs
Update deploy script to allow running whichever target
/assign @michelle192837 @chases2

Create canary testgrid deployment.

---

pkg/summarizer/BUILD.bazel
pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

/assign @michelle192837 @chases2 
Use [error wrapping](https://blog.golang.org/go1.13-errors) to detect when the grid does not exist. Return a skeleton summary in this scenario.
Cover with unit tests

Handle scenario where grid is not found

---

pb/config/config.pb.go
pb/config/config.proto

Current usage suggests that these protos do not have the gcs_prefix, and I am pretty sure not including the prefix is currently required. So documenting this as such.

Testgrid does not accept gs:// prefix on gcs_prefix field

---

config/config.go
config/config_test.go
config/yamlcfg/yaml2proto_test.go

- Validate that names don't have forbidden prefixes (e.g. can't start with the prefixes of special files we use in TestGrid)
- Validate TestGroup and DashboardTab-specific options
/assign fejta@, chases2@

Advanced configuration option validation.

---

pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

Allows other services to determine the dashboard & tab name from only the DashboardTabSummary proto.
Arguably, this field should be a member of the [DashboardSummary](https://github.com/GoogleCloudPlatform/testgrid/blob/master/pb/summary/summary.proto#L91), not the DashboardTabSummary, but I think the advantage of deduplication doesn't outweigh having to restructure a proto definition.

Populates Dashboard Name in generated summaries

---

resultstore/client.go

Resultstore search is project specific. We need to pass in the projectID field instead of hardcoding it.

Make resultstore search project specific

---

README.md
config.md

The old config docs had some dead links and unresolved links due to the migration. This PR creates a new config.md for GCP/testgrid and links back to k8s/test-infra where needed. It also removes some elements that only exist from internal.
Ex. does not exist in the OSS context and was removed.
Ex. <config.proto> paths changed

Migrate config.md from old k8s/testinfra to CGP/testgrid

---

go.mod
go.sum
pkg/summarizer/BUILD.bazel
pkg/summarizer/summary.go
pkg/summarizer/summary_test.go
repos.bzl

This is part of an effort involving adding some new metrics for the failure ratios of columns. I changed the standard bool tracking of row pass rates to track the number of passes and fails. Then calculate the ratio of failing cells to total cells. 
* I also treated PASS_WTH_SKIPS and PASS_WITH_ERRORS as passing and added them into the unit tests. 
Q: Do we want running to be treated as failure still?
I also pulled the status string generation out and gave it it's own test.
Talking with fejta it seem there was a push to avoid adding any new deps and modules. Being able to use assert was nice because it allowed me to create a variadic shim to easily test functions with multiple different return types. If there is a way to do this easily without assert + shim I am all ears. 
Only about 2 …

Add Column failure collection for use in 2nd stage processing (Part 1)

---

pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

For now it will just report the testID and target which can be used to build the url
TODO: Improve bug gathering and link building (different PR)
#134

Add placeholder method for building FailingTestLinks

---

cmd/summarizer/main.go
pkg/summarizer/flakiness.go

The current implementation, where it iterates through each column and grabs one output from each channel, causes summarizer to run much more slowly than if it were to consume the all of the output from one channel at a time. This change aims to fix that. 
It also adds logging of the timing for updateOnce and a way to track per row indices of messages (if a Row_Result is NO_RESULT then we don't increment the index, however for all other Row_Result's we do) for accuracy.

Change channel usage logic to drain channels

---

cmd/updater/main.go
pkg/updater/updater.go

This allows different updaters to upload to different suffixes, for example
gs://prefix/grid-prod/foo and gs://prefix/grid-beta/foo. The frontend can then toggle between
grid-rod and grid-beta via some URL param, etc.
Also some general cleanup.

Add a --grid-prefix flag.

---

cluster/canary/summarizer.yaml
cluster/canary/updater.yaml

Canary is actually not doing anything right now because it is not authorized to act as updater@k8s-testgrid.iam.gserviceaccount.com and it probably shouldn't have this auth.

Use different service account for canary

---

cluster/prod/summarizer.yaml
cluster/prod/updater.yaml

Turn back on updater writing (confirmed this goes to the PREFIX/grid/testgroup-name path
(meaning it has the grid/ prefix and thus can run concurrently)
Once the updater completes a loop, we'll be able to view golang updater results by appending `&grid=beta` to a tab's fragment.
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-master&grid=beta

Rollout v20200714 summarizer and updater to prod.

---

cmd/summarizer/main.go
pkg/summarizer/summary.go

--grid-path=grid will read state created by the new summarizer.
Eventually we should write summaries to a summary/ path, which --summary-path supports.

Flags to configure where summarizer reads/writes.

---

pb/state/state.pb.go
pb/state/state.proto
pkg/updater/BUILD.bazel
pkg/updater/inflate.go
pkg/updater/inflate_test.go

Correct a documentation error on metric encoding.
This will soon be used to refactor the updater to only download the
latest results, rather than everything.
Sending just this as a way to break things up.

Functions to reinflate compressed grid messages.

---

util/gcs/BUILD.bazel
util/gcs/read.go
util/gcs/read_test.go

We do not need a special function to parse the json.
We do not need a WaitGroup and/or a thread that waits for this group.
Add readJSON test coverage

Refactor how we read test suites.

---

go.mod
pkg/updater/BUILD.bazel
pkg/updater/read.go
pkg/updater/read_test.go

Also catch and resolve some bugs in the process:
* Need to get column header's configuration value.
* Distinguish between stop time and build download duration
* Truncate excessive results correctly
* Include the newest result that is too old.
* Fix a NPE when started/finished error.
* Avoid hang when multiple builds find a too old build concurrently

Add ReadColumns coverage.

---

util/gcs/BUILD.bazel
util/gcs/read_test.go

Also refactor to use `cmp.Diff()` instead of `reflect.DeepEqual()`

Add coverage for linked builds

---

internal/result/results.go
pb/state/state.pb.go
pb/state/state.proto
pkg/summarizer/flakiness.go
pkg/summarizer/flakiness_test.go
pkg/summarizer/summary_test.go
pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/inflate.go
pkg/updater/inflate_test.go
pkg/updater/read.go
pkg/updater/read_test.go
pkg/updater/updater.go
pkg/updater/updater_test.go

Change state -> statepb, add package comment to updater, don't need 'break' in switch statement.
ETA: Also fixed some `go vet` errors (format directives in non-format functions, or %s for complicated values)

Fix lint errors across files

---

cluster/canary/summarizer.yaml
cluster/canary/updater.yaml

This may resolve updater eviction issues.

Update canary to v20200806-v0.0.16-12-g054d30c.

---

pkg/updater/updater.go

This should reduce the amount of time the system is holding on to dead memory.

Run the garbage collector after updating each group.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Currently if jobs take more than 4 hours we will never find their final result: we will continue using the cached running value.
Avoid this by finding the oldest downloaded column that is still running. Drop it and everything more recent than it.
This will allow up to 24 hours for a job to complete (after which time the overall cell will automatically fail with a timeout message.
https://github.com/GoogleCloudPlatform/testgrid/blob/069a9fb0615756af0ba341a478de546517d5e299/pkg/updater/gcs.go#L167-L170

Continue reprocessing results until they are no longer running.

---

cluster/canary/summarizer.yaml

This one will read state from grid/foo instead of foo and write to summary/summary_foo instead of summary_foo.

Create a beta-summarizer in canary.

---

util/gcs/read.go
util/gcs/read_test.go

We expect a format like: `junit.xml` or `junit_something.xml` or `junit_context_12-34_56.xml`.
Currently this rejects something like `junit.e2e.xml`. This change will put `.e2e` into context.
And also allow the updater to process these results.
In short, anything that both starts with `junit` and ends with `.xml` we want to try and process.
fixes https://github.com/GoogleCloudPlatform/testgrid/issues/213

Support junit file names that do not match the regex.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read_test.go

The python version uses `test-duration-minutes` rather than `seconds-elapsed` and lots of jobs seem to take many minutes to finish.
ref https://github.com/GoogleCloudPlatform/testgrid/issues/211

Switch seconds-elapsed to test-duration-minutes

---

metadata/junit/junit.go
metadata/junit/junit_test.go

ref https://github.com/GoogleCloudPlatform/testgrid/issues/236
Ensure that `row.Message()` is a valid UTF8 string.
Unit test this function.
Redhat occasionally has errors like the following:
```
ERRO[0003]pkg/updater/updater.go:71 github.com/GoogleCloudPlatform/testgrid/pkg/updater.Update.func1() Error updating group                          config="gs://k8s-testgrid/config" error="marshal grid: marshal: proto: field \"Row.Messages\" contains invalid UTF-8" group=release-openshift-ocp-installer-console-aws-4.6
```
This causes the updater to stop updating when it finds that column, which then results in everything after it failing to load.

Handle xml documents with invalid utf-8 messages

---

WORKSPACE
config/yamlcfg/BUILD.bazel
config/yamlcfg/yaml2proto.go
config/yamlcfg/yaml2proto_test.go

Test: Added unit tests, locally tested that default.yaml applies
correctly in k8s/test-infra config.
Note: We will need to later update the version of TestGrid used
in k8s/test-infra to pull these changes in.
See #7 
Co-authored-by: Mitchel <mpherman@google.com>

Allow local defaults for a config directory.

---

pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

This will properly record hotlist IDs from alerts into summary, for use in components like AutoBug.

Write hotlist IDs to summary.

---

cluster/canary/updater.yaml

Still runs immediately after each update
/hold

Run canary updater less frequently.

---

pkg/updater/updater.go
pkg/updater/updater_test.go
util/gcs/client.go

This allows the updater to continually make progress even under intermittent crashes.
Currently if (for example) an update cycle takes 10m and it crashes every 3m, we will continually update the first third of groups and never the next two thirds. With this change we will update a different third every 3 minutes.
ref https://github.com/kubernetes/test-infra/issues/20010

Update least recently updated groups first.

---

cluster/prod/summarizer.yaml
cluster/prod/updater.yaml

Also limit concurrent build updates to 4 per group (matching canary)

Promote v20201203-v0.0.31-5-g5f8e850 to prod

---

pkg/updater/read.go
pkg/updater/updater.go

Calling `wg.Add(1)` inside a goroutine races with `wg.Wait()` on the main thread.
Fix this by creating a `stopWG` 
See https://golang.org/pkg/sync/#WaitGroup.Add

Fix readColumns race condition

---

cmd/updater/main.go
cmd/updater/main_test.go
go.mod
go.sum
pkg/updater/BUILD.bazel
pkg/updater/mem.go
pkg/updater/read.go
pkg/updater/updater.go
repos.bzl

Allows --group-memory and --build-memory to ensure that at least that much memory is free in order to
start processing a new group/build.
Also fix a divide-by-zero edge case and allow NumCPU concurrent builds again by default

Throttle group and build concurrency based on memory usage.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Process a max of 5 columns until we know more about the number of rows per column.

Update a max of 5 columns on first run

---

metadata/junit/junit.go
metadata/junit/junit_test.go
util/gcs/read.go

* Improve how we distinguish between `<testsuite>` or `<testsuites>`
* This allows unmarshalling a stream
* Add ability to truncate long strings to a specified length

Update XML unmarshalling.

---

metadata/junit/junit.go
pkg/updater/read.go

* 10K when parsing XML
* 1K when putting them into a column.
These strings will get truncated to 140 chars by testgrid later, this minimizes memory overhead during that time.

Automatically truncate junit suites.

---

pkg/updater/BUILD.bazel
pkg/updater/read.go
pkg/updater/updater.go
pkg/updater/updater_test.go
util/gcs/client.go
util/gcs/gcs.go

* Copier extends Client to allow copying.
* ConditionalClient extends client to require operations to meet prerequisites in order to run.
Use ConditionalClient to conditionally cloud copy an object before
starting. This will allow multiple worker pods to update in parallel
without central coordination:
* If multiple attempt workers to update the same group, only one will
win the conditionally clone the object.
* Winner updates the object, others continue on to subsequent objects
Also mitigates against a problematic group or groups stopping updates for everyone:
* Before attempting to update the problematic group, the updater locks the group which bumps its last update timestamp
* Thus if the updater crashes, the problematic group will be at the end of the queue upon restart.

Create ConditionalClient and Copier, allows multiple updater pods

---

cluster/canary/summarizer.yaml
cluster/canary/updater.yaml

Also:
* drop --group-timeout to 5m (from 60m)
* drop --build-timeout to 1m (from 10m)
* increase updater replicas to 2 (from 1)

Update canary to v20201216-v0.0.33-28-g01968e7

---

cluster/canary/summarizer.yaml

The canary updaters have a 3h cycle, so this is plenty.

Reduce frequency of canary summarizers to 1 hour.

---

cmd/updater/main.go

The sleeping wait=5m is generally erroneous.
The time spent doing the update is subtracted from the wait time.
This is a substantial amount of time, often more than the wait period.
This means the next update happens much quicker.
Add the until field to make it more obvious when sleeping should stop.

Improve sleep message.

---

cluster/testgrid-canary-autobump-config.yaml
cluster/testgrid-prod-autobump-config.yaml

The git name and email currently in the config are for the k8s-prow robot, which is not the one doing the autobump for testgrid. Removing the name and email will default the name and email to the one associated with the oauth token used for the job.

Remove info for k8s robot from testgrid autobump config

---

config/BUILD.bazel
config/converge.go
config/converge_test.go

This will allow users to generate large configs from multiple disparate config proto sources, automatically renaming components to avoid duplicates.
Also exposes configuration-sensitive "rename" functions that will correctly rename references to config objects.

Add configuration merging functions to config library

---

pkg/updater/updater.go
pkg/updater/updater_test.go
util/gcs/read.go
util/gcs/read_test.go

Restrict this to specific groups as this is not a fully-finished feature
Switch `originalPrefix` to `baseName` is this is the reason we track it.
Export `gcs.Sort()` so that we can re-sort builds from multiple jobs

Allow groups to collate multiple prow jobs together.

---

README.md
build_test_update.md
standalone.md

Adds initial documentation for creating and using TestGrid controllers to generate and display a TestGrid instance
Also updates surrounding links and documents to point to this tutorial

Add documentation for new TestGrid instances

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read.go
pkg/updater/read_test.go
pkg/updater/updater.go
util/gcs/read.go
util/gcs/read_test.go

If `GcsPrefix: this-job,that-job` then ensure that the name config includes a `Job name` field (insert it to the front if not)

Add job name when results collate multiple jobs

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read.go

Cell metrics then get moved into row metrics here:
https://github.com/GoogleCloudPlatform/testgrid/blob/75fc13bde00135a34ab8b1f28e4a98c557cbad44/pkg/updater/updater.go#L640-L664
Allow short_text_metric to become the cell icon.

Pull numeric junit properties into row metrics.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go

Some jobs appear to use result and skip the passed boolean. Handle this scenario, but flag that this is not expected

Handle missing passed in finished.json.

---

internal/result/results.go
internal/result/results_test.go
pkg/summarizer/flakiness.go
pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

We're counting any non-passing, non-no-result status as 'failing' for the purposes of calculating if a tab is in 'broken' state. Instead, treat non-passing, non-failing statuses as 'neutral'.

Update broken-state calculation with neutral statuses.

---

standalone.md

The previous PR #368 seems to generate a link "https://github.com/GoogleCloudPlatform/testgrid/blob/master/(./config.md)" which is invalid.

fix: link to configuration from standalone docs

---

cmd/summarizer/main.go
pkg/summarizer/summary.go

Verified locally (e.g. `bazel run //cmd/summarizer:summarizer -- --config=/tmp/testgrid-states/config --confirm=true --dashboard=TestGrid`)

Have Summarizer use util/gcs library, not storage itself.

---

images/push.sh
pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/updater_test.go

Also simplify how we create the job-foo.InjectedRow name, and an icon to the Pod row

Only add missing pod info note after job finishes.

---

metadata/junit/junit.go
metadata/junit/junit_test.go

testgrid mark test as passed if they are of type "error" [1]. This
change add the type "error" and store it in the Result as Errored field.
[1] https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd#L75
Signed-off-by: Quique Llorente <ellorent@redhat.com>

Add JUnit "error" test cases

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Technically these only exist on rows with `@TESTGRID@` in them, but
be more permissive in what we allow by directly checking for cell IDs rather
than looking at the row name.

Stop requiring optional cell ID field when alerting a row.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read.go
pkg/updater/read_test.go

Reading these currently return io.EOF errors, which prevents reading more recent columns.
Detect this scenarioe explicitly and add the files to the missing list.
Report these missing files in the Overall cell.

Handle empty json files.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read.go
pkg/updater/read_test.go
util/gcs/read.go
util/gcs/read_test.go

Right now a bad junit artfiact will return an error and prevent the system from
considering newer builds until the problematic artifact is resolved.
Change things up so that we fail abort the build and note the problematic artifact, but
continue processing other builds for this job.
ref https://github.com/GoogleCloudPlatform/testgrid/issues/413

Malformed junit files should fail the build but not the job.

---

cluster/canary/config_merger.yaml
cmd/config_merger/main.go

Also allows config_merger to read from a URL with a special flag.
Do not merge until https://github.com/kubernetes/test-infra/pull/20986 merges, or the URL won't work.

Add Config Merger for k8s in Canary

---

cluster/canary/summarizer.yaml
cluster/canary/updater.yaml
cluster/prod/summarizer.yaml
cluster/prod/updater.yaml
cmd/summarizer/main.go
cmd/updater/main.go

Add support for --debug, --trace and --json-logs to summarizer
Start using --json-logs after next release.

Use --json-logs for updater, prepare to do so for summarizer

---

pkg/summarizer/summary.go

Currently we are spamming our logs with the full content of every dashboard's summary every update loop.

Only log the entire summary proto when confirm is false.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go

As noted in #406, also resolve a TestGrid status for a JUnit 'error'. This should fix #408.

Read JUnit 'error' cases as failures.

---

cluster/canary/BUILD.bazel
cluster/prod/BUILD.bazel
cluster/prod/config_merger.yaml
cmd/config_merger/main.go

Adds the new controllers to the BUILD files for easier deployment
Adds some further logging to the config_merger image

Deploy config merger to production

---

config/BUILD.bazel
config/print/BUILD.bazel
config/print/README.md
config/print/main.go

I wrote an experiment to see how well protos would deserialize into json objects (pretty well) and accidentally wrote a useful CLI config printing utility for debugging.
/lint

Print Config Utility

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Modifies TruncateRunning to regenerate a row with any running job in it, not just the "Overall" row.
Allows for TestGrid to detect running jobs even when the "Overall" row isn't being injected.

Modify TruncateRunning to truncate any running cell

---

pkg/updater/updater.go
pkg/updater/updater_test.go

truncateRunning() will drop columns with running results. Various systems
may result in a permanently running cell (for example, the job died before
finishing, etc).
Handle this scenario by only accepting running results that started within
the last 3 days.

Keep running columns many days old.

---

pkg/summarizer/BUILD.bazel
pkg/summarizer/summary.go
pkg/updater/BUILD.bazel
pkg/updater/read_test.go
pkg/updater/updater.go
pkg/updater/updater_test.go
util/gcs/BUILD.bazel
util/gcs/fake/BUILD.bazel
util/gcs/fake/fake.go
util/gcs/fake/fake_test.go
util/gcs/fake/sort_test.go
util/gcs/sort.go

Refactor `LeastRecentlyUpdated` into `util/gcs`
Move GCS fakes into `util/gcs/fake`
Refactor updater to use `LeastRecentlyUpdated`
Teach summarizer to use `LeastRecentlyUpdated`
Reviewing just the second commit should minimize eye strain (first commit moves the fakes)

 Summarize tab by least recently updated order. 

---

pkg/updater/gcs.go
pkg/updater/inflate.go
pkg/updater/inflate_test.go
pkg/updater/read.go
pkg/updater/updater.go

Production-bound code should use the exported Cell and InflatedColumn names.

Restrict cell and inflatedColumn aliases to unit tests.

---

cmd/updater/main.go
pkg/updater/inflate.go
pkg/updater/inflate_test.go
pkg/updater/updater.go
pkg/updater/updater_test.go

`InflateDropAppend` callers must now provide a column sorting strategy.
* Allow strategy to vary per test group.
Provide a `SortStarted` which sorts columns by their start date.
Ensure inflated columns are:
* `SortStarted` after inflation, before processing
* Sorted according to provided strategy before converting to a grid message.

Allow custom sorting mechanics.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read.go

Without this there is no way to configure testgrid to open the correct spyglass URL when clicking on a cell.

Add CellID when commit_override_strftime is set

---

pkg/summarizer/summary.go
pkg/updater/updater_test.go
util/gcs/gcs.go

This allows logrus' json formatter to provide a useful string.
Other cosmetic fixes

Implement json un-/marshalling for gcs.Path.

---

pkg/updater/read_test.go

Should mitigate flakiness
`bazelisk test //pkg/updater:all --runs_per_test=100`
fixes https://github.com/GoogleCloudPlatform/testgrid/issues/466

Ensure context has something to read.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read.go
pkg/updater/read_test.go

Currently they'll stop after the first error. Instead inject a failing overall row into these columns
and continue processing.
ref https://github.com/GoogleCloudPlatform/testgrid/issues/478

Refactor readColumns to only error if all columns fail.

---

pkg/updater/read.go
pkg/updater/read_test.go

If the first or last block of builds failed, we will currently either panic or miss those builds. This fixes that

Handle edge cases for failed builds.

---

pkg/updater/inflate.go
pkg/updater/inflate_test.go
pkg/updater/updater.go

Grid state fields are compressed using a variety of encodings (run-length, sparse, etc).
Getting this correct is non-trivial. Mulitple controllers need to read the grid state and
work with and/or modify this data, so export this function.
Also preserve the cell.ID when inflating cells.

Export InflateGrid.

---

pkg/merger/merger.go
pkg/merger/merger_test.go
pkg/summarizer/summary.go
pkg/updater/BUILD.bazel
pkg/updater/updater.go
util/gcs/client.go
util/gcs/fake/fake.go
util/gcs/fake/sort_test.go
util/gcs/gcs.go
util/gcs/local_gcs.go
util/gcs/real_gcs.go
util/gcs/sort.go

When we lock a dashboard by cloud copying it over itself it is useful to track the new generation.
This allows us to conditionally write the new state with the assumption is hasn't changed.
Also, update LeastRecentlyUpdated to set a ceiling on the number of concurrent Stats.
Attempting to stat all paths concurrently is not optimally efficient and can run into
open file limits on some systems.
https://pkg.go.dev/cloud.google.com/go/storage#Copier.Run
https://pkg.go.dev/cloud.google.com/go/storage#Writer.Attrs

Refactor writes to return new object metadata.

---

pkg/summarizer/summary.go
pkg/updater/updater.go
util/gcs/fake/fake.go

Also use the same metric functions in Summarizer as in Updater, for consistency.

Fix lint errors, again.

---

pkg/summarizer/summary.go

Short-term, it's not possible to tokenize this field if either one contains a space in it.
Long-term, I'm not sure that the summarizer should be responsible for creating these links. The stub suggests that an implementation for building a fail link should be passed in, but I think we want to expose the failBuildID and latestFailBuildID directly and let components that want to display a link construct them.

Escape buildFailLink

---

cmd/config_merger/main.go
pkg/merger/merger.go

Also unmarshals configs strictly, so that failures due to malformed YAML configs will be caught earlier.

Parallelize Config Merger

---

config/config.go
hack/compare_states.go
pkg/merger/merger_test.go
pkg/summarizer/summary.go
pkg/updater/updater.go
pkg/updater/updater_test.go
util/gcs/client.go
util/gcs/fake/fake.go
util/gcs/gcs.go
util/gcs/local_gcs.go
util/gcs/read.go
util/gcs/read_test.go
util/gcs/real_gcs.go

This allows the consumer of the open file to know various metadata, such as when it was last modified and/or
the object generation. This can help minimize conflicts by minimizing the time between when we discover the
generation of a downloaded object and when we attempt to update it, assuming the remote generation is unchanged.

Refactor Opener interface to return attributes.

---

cmd/updater/main.go
config/BUILD.bazel
config/queue.go
config/queue_test.go
go.mod
go.sum
pkg/updater/BUILD.bazel
pkg/updater/updater.go
pkg/updater/updater_test.go
repos.bzl
util/gcs/sort.go
util/metrics/log.go

Currently updater will wait until all groups have been updated once before updating them a second time.
Instead groups are put into a priority queue based on how recently they were updated.
As soon as an item is sent for an update, its moved to the back of the queue.
This helps mitigate the situation where 99% of the groups have been updated but the last one is taking a long time.
Instead of waiting for this one to finish, the other groupConcurrency workers will being updating the other groups
while this one is finishing.

Refactor updater to continually send groups to be updated.

---

config/queue_test.go
pkg/updater/updater.go
pkg/updater/updater_test.go

Do not call t.Fatal() within a go routine.
Do not use unnecessary typing
Use consistent struct receiver name.

Code cleanup.

---

util/metrics/log.go
util/metrics/log_test.go

Makes the output more like this:
```
INFO[0030] Current status                                field=component metric=cycle updater="0.743 average (74 values)"
INFO[0030] Current status                                field=component metric=delay updater="1.06e+04 average (1 values)"
INFO[0030] Current status                                field=component metric=errors
INFO[0030] Current status                                field=component metric=skips
INFO[0030] Current status                                field=component metric=successes updater="2.47 per second (74 total)"
```

Include totals in logged metrics

---

pkg/updater/updater.go

Golang will panic if a map is concurrently read and written.
We guard the map write (L303) but we also need to protect when we read from this map.
Switch to use an RWMutex so that we can concurrently read.

Lock access to reading the generation.

---

cluster/canary/updater.yaml
cluster/prod/updater.yaml

We are running into evictions because of memory pressure, so reduce the
number of builds and groups we process in parallel.
This, combined with the fact that we now process new groups last means we struggle to process new groups.
https://github.com/GoogleCloudPlatform/testgrid/blob/95cfeb295b8d6e732fe4cc3f8ab74e67ed33ea8e/config/queue.go#L185
/cc @chizhg

Reduce concurrency.

---

cmd/updater/main.go
pkg/updater/read.go
pkg/updater/read_test.go
pkg/updater/updater.go
pkg/updater/updater_test.go
util/metrics/log.go

Instead of processing all columns and then returning them, send each column to a channel as they are processed.
Requires refactoring the code to start from the oldest result rather than the newest
- Hint (aka build id) is authoritative, not the start time, so stop overriding this value.
- Do use the original stop time in order to spend less time downloading old builds we will just throw away
Obviates the need for truncating results, instead we will track how long we have to update and gracefully stop
requesting more columns after half the time has elapsed, leaving the second half for uploading.
Detect this scenario and immediately request another update cycle for this group (rather than waiting the normal cycle).
Serialize build processing (keeping group concurrency) for the time being …

Refactor ColumnReader to use channels.

---

pkg/updater/read.go
pkg/updater/read_test.go

Otherwise we risk repeating work if we spend the entire cycle reading and skipping old builds
without ever outputting a column. So instead report that this is happening just like we do with
other types of unprocessable builds.

Emit synthetic columns for ancient builds.

---

cluster/canary/BUILD.bazel
cluster/canary/api.yaml
pkg/api/v1/BUILD.bazel
pkg/api/v1/config.go
pkg/api/v1/config_test.go

Adds extra logging when a default scope is used but still can't read

API deployment cluster in canary (only)

---

go.sum
pkg/api/router.go
pkg/api/v1/BUILD.bazel
pkg/api/v1/config.go
pkg/api/v1/config_test.go
pkg/api/v1/server.go

xref #549 
- Refactors testing to use a router instead of server functions directly so test cases are more intuitive
- Deduplicates reused code between the two API functions

Implement GetDashboardGroup

---

pkg/updater/gcs_test.go
pkg/updater/read.go
pkg/updater/read_test.go
util/gcs/read.go
util/gcs/read_test.go
util/gcs/sort_test.go

Currently we start many go threads to read artifacts and builds in parallel. This causes a lot of
memory pressure. So instead switch to channels with a 1 item buffer. This allows each go routine
to continue working on the second item as soon as it finishes the first one. Things will only block
if the second item is completed before the first item is read.
Assuming everything is processing quickly this should result in similar performance but with better
performance when things slow down (memory consumed for 1-2 items instead of N).
Also: reject junit files more than 100MB, failing these builds with a note about the error.

Use buffered channels instead of concurrency.

---

cmd/updater/main.go
config/queue.go
pkg/updater/updater.go
pkg/updater/updater_test.go
util/gcs/BUILD.bazel
util/gcs/real_gcs.go

The official storage client does this incorrectly: it uses the XML api for reads but sends ifGenerationMatch
parameters (for the json api) rather than the required x-goog-if-generation-match headers. So instead check
this manually when the response comes back.
Also:
* fix some related issues (cannot use the testgroup's conditions to read objects, similar thing for reading
the config).
* Only fix the update time if the group already exists and has a written state
* Only fix the heap when the update time changes.

Check preconditions when reading.

---

util/metrics/log.go
util/metrics/log_test.go

* Not an average when there's only 1 value.
* Short-circuit when seconds is zero.

Improve metric strings.

---

cmd/api/main.go
pkg/api/BUILD.bazel
pkg/api/router.go

The current GCS storage client doesn't provide means to authenticate in other ways. This is needed so caller can initialize storage client and pass it to GetRouter method.

Add option in GetRouter to override the storage client

---

pkg/updater/updater.go

Adding a buffer to this channel means that readCols can return after sending the items to the channel but
before anyone reads them. Once readCols returns this go routine will try and send the err to ec, and this
creates a race condition where the main routines reads the err before the buffered items on the channel,
thus dropping some already processed columns and losing work and introducing flakiness.

Do not use a buffered channel for newCols.

---

pkg/updater/read.go
pkg/updater/read_test.go

/assign @michelle192837 
There are no longer go routines in readColumns so we do not need to create a new context to cancel, which should mitigate flakiness along with ensuring we've checked the err.

Try and deflake TestReadColumns

---

pkg/updater/updater.go
pkg/updater/updater_test.go

ETA: Instead of just throwing away empty columns, this groups all empty columns together, keeping the hint of the latest empty column. Thanks Erick for the suggestion!
This ignores empty columns instead of processing them into the grid. (This will not progress the latest 'hint' for the grid past the last non-empty column, so it's possible to repeat work, but in my estimation this should not be a significant issue. If it is, swap to an artificial 'last processed' column that we keep at the beginning to make sure the hint progresses).

Ignore columns with no cells.

---

pkg/updater/updater.go

This will allow us to detect deleted test groups.

Periodically update generations.

---

metadata/job.go
metadata/job_test.go
pkg/updater/gcs.go
pkg/updater/gcs_test.go

When reading list of strings from json go recognize it as a list of interfaces, which cause casting issues.
Added a function that deal with the case if it's a list of interfaces or list of strings. if not it's throw an error

TestGrid Dynamic List - support extract email list from []interface{}

---

pkg/api/v1/config.go
pkg/api/v1/config_test.go
pkg/api/v1/server.go

Add implementation for these config APIs:
* /dashboards -> Lists dashboard names
* /dashboards/{dashboard}/tabs -> Lists the dashboard tab names
* /dashboards/{dashboard} -> Returns a Dashboard config's metadata
+ Unit tests added
+ Fix 404 not found issue for dashboard groups locating (missing Normalize comparison)

Add implementation for these config APIs

---

.bazelrc

This is now `--@io_bazel_rules_go//go/config:race`
```
DEBUG: /root/.cache/bazel/_bazel_root/38c3d4864ff292290a1ecc94a9fefad6/external/io_bazel_rules_go/go/private/context.bzl:497:14: WARNING: --features=race is no longer supported. Use --@io_bazel_rules_go//go/config:race instead.
```

Correct flag to enable race detction during testing.

---

util/gcs/read.go

Already robust to this because of:
https://github.com/GoogleCloudPlatform/testgrid/blob/8cb1f6faf07480e12288879b53e81438e05bb030/util/gcs/read.go#L259-L269 
But we shouldn't rely on it.

Ensure offset has a trailing /.

---

pkg/pubsub/pubsub.go
pkg/pubsub/pubsub_test.go

Create a wrapped client type, which implements a Susbscriber interface that will Subscribe and returns a Sender.

Refactor pubsub package for easier unit testing.

---

cluster/canary/updater.yaml
config/queue.go

* Fix requests to more closely match autopilot's usage-based values.
* Increase periodic cycle to 4h
* Correct kubernetes-jenkins subscription ID for canary.
/cc @cjwagner 
/cc @chaodaiG 
(also includes the https://github.com/GoogleCloudPlatform/testgrid/pull/644 bump)

Update canary updater flags.

---

pkg/updater/pubsub.go
pkg/updater/pubsub_test.go

Presubmits tend to get uploaded in a `gs://prefix/directory/job/1234.txt` with a link to `gs://prefix/pull/123/job/1234`

Match PR directory links.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/pubsub.go
pkg/updater/updater_test.go

The podinfo.json is updated by crier, some time after the sidecar uploads finished.json.
Detect this scenario and flag a missing podinfo.json as RUNNING until the result has reached its deadline:
* An hour after finished.json is uploaded or 24 hours after it started.
Also allow a larger buffer between when we receive a pubsub notification and when reprocess the tab.
/cc @chaodaiG 
ref #656

Allow time to collect podinfo.

---

pkg/api/v1/config.go

Update config APIs response type.
This is a follow-up PR to a comment Erick added in PR #615 on providing the correct response type on APIs description.

Update config APIs response type

---

cluster/canary/updater.yaml
cluster/prod/updater.yaml

ref https://github.com/GoogleCloudPlatform/testgrid/issues/663
We can do everything we need within a single replicas, so multiple-replicas support is not critical at the moment. This was mostly just to prove it can work, but currently prod will work better without it.

Reduce updater replicas to 1

---

pkg/updater/updater.go
pkg/updater/updater_test.go
util/gcs/gcs.go

Download and Upload now returns the generation. We can use this in InflateDropAppend to determine what version we downloaded
and ensure when we try and replace it that no one else has changed it.
This is faster and also simplifies Update since it no longer needs to try and lock the object and/or track the generation.
We can just determine the generation when we download the object and ensure that our upload replaces this version.

Stop touching the grid before download, tracking generation.

---

cluster/prod/knative/updater.yaml

Also increase build and group timeouts.

Reduce to a single updater replica.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

This float -> timestamp conversion is causing the displayed start times to be wrong when displayed, without (it seems) affecting the business logic of the updater. The rest of the updater seems to treat this field as milliseconds correctly.
It would be great if this proto field was simply a "timestamp", so it doesn't need to be converted to (and later from) a timestamp. (#683)

Fix timestamp assignment from columns

---

cmd/config_merger/BUILD.bazel
cmd/config_merger/main.go
config/BUILD.bazel
config/fields.go
config/fields_test.go
go.sum
pkg/merger/merger.go
pkg/merger/merger_test.go

Config Merger now counts and logs usage of particular config options as merging takes place.

Add field metrics to config merger

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Properties will generally be the same on the parent row for rows with a group delimiter, so save time/space by not storing additional info on them.

Don't store properties on group-delimiter rows.

---

pkg/updater/inflate.go
pkg/updater/inflate_test.go
pkg/updater/updater.go

This can be an expensive operation so check the context each column and abort early when it is done.

Allow InflateGrid to time out.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read_test.go
pkg/updater/updater_test.go

We already do this for multi-job configurations, do it for single-job as well for consistency and better interaction with some features.

Always include job name on Overall row.

---

config/BUILD.bazel
config/queue.go
config/queue_test.go
util/BUILD.bazel
util/queue.go
util/queue_test.go

The core logic of updating something at a specific time is more general than test groups. 
For example, the summarizer will want to use this on a per-dashboard basis (not test group). This moves most of the logic into util/queue.go, with specific TestGroup functionality in config/queue.go.

Refactor TestGroup out of base Queue

---

cmd/api/main.go
pkg/api/router.go
pkg/api/v1/config.go
pkg/api/v1/config_test.go
pkg/api/v1/server.go

Using path.Join on a URL results in its protocol getting mangled, ex: https://stackoverflow.com/questions/34668012/combine-url-paths-with-path-join/34668130
Instead, store the hostname as a *URL and convert to string at the last moment to allow correct URL manipulation

Store hostname as URL

---

pkg/updater/updater.go
pkg/updater/updater_test.go

For any columns after the column that exceeds the threshold, merge all such columns
into a single empty column

Truncate grid more aggressively.

---

pkg/summarizer/summary.go

Right now all the logs are debug level, and default logging only notes when a dashboard errors, not when it succeeds.

Log when we successfully summarize a dashboard.

---

cmd/config_merger/BUILD.bazel
cmd/config_merger/main.go
cmd/summarizer/BUILD.bazel
cmd/summarizer/main.go
cmd/updater/BUILD.bazel
cmd/updater/main.go
pkg/merger/BUILD.bazel
pkg/merger/merger.go
pkg/merger/merger_test.go
pkg/summarizer/summary.go
pkg/updater/updater.go
pkg/updater/updater_test.go
util/metrics/BUILD.bazel
util/metrics/metrics.go
util/metrics/metrics_test.go

Adds duration controller to summarizer
Adds success/failure metrics to config_merger
Moves cycle timer to util/
Creates factory to standardize metric creation in main.go
/lint

Standardize cycle metrics across controllers

---

cluster/testgrid-canary-autobump-config.yaml
cluster/testgrid-prod-autobump-config.yaml

Testgrid bumping PRs are not monitored/approved by oncall members, there is no need assigning to them, let blunderbuss do the job if configured

Testgrid autobump PR not assigned to oncall

---

cmd/config_merger/BUILD.bazel
cmd/config_merger/main.go
cmd/summarizer/BUILD.bazel
cmd/summarizer/main.go
cmd/updater/BUILD.bazel
cmd/updater/main.go
pkg/updater/updater.go
util/metrics/metrics.go
util/metrics/metrics_test.go
util/metrics/prometheus/prometheus.go
util/metrics/prometheus/prometheus_test.go

A common TestGrid metric is a duration, which is currently being stored as an Int64 number of seconds. This rendered anything that happens in less than one second (ex: most Config Mergers) invisible.
This change adds a metric type that measures elapsed time with the standard "duration" type.

Create Duration metric

---

pkg/api/v1/state.go
pkg/api/v1/state_test.go

The "Started" timestamps from ListHeadersResponse report in seconds, but are actually milliseconds.
xref #683

Fix timestamp misconversion

---

util/gcs/BUILD.bazel
util/gcs/local_gcs.go
util/gcs/local_gcs_test.go

Tested this locally, this is a quick and dirty fix for when a test group name contains a space (which is encoded by url.Parse).

Unescape local filepaths.

---

build_test_update.md

Not actually sure if it strictly requires Python 2 or what, but that's what fixed it for me.
There may be other requirements that aren't obvious to me (e.g., is the Go compiler
needed?).

Document update-protos requiring python2

---

config/BUILD.bazel
config/cache.go
config/cache_test.go
config/config.go
pkg/api/v1/BUILD.bazel
pkg/api/v1/config_test.go
pkg/merger/merger_test.go

Modifies the Read GCS function to keep a cache of recently-requested configs. Mostly serves to speed up the API.
Controllers and commands using these functions:
`ReadGCS`: Config Merger, API
`Read`: Config Print, State Comparer
The Summarizer and Updater have their own logic to periodically recheck the configuration (not just as-needed); all of these could be collapsed into a config file subscription.

Add cache backing ReadGCS

---

pkg/summarizer/summary.go

Fix to a panic caused after #790 was merged due to the queue not being initialized the first time the loop runs.
Lesson learned: test with --wait flag; the bug doesn't manifest if you run a summary only once.

Initialize summarizer queue

---

config/snapshot/config_snapshot_test.go
pkg/tabulator/tabstate.go
pkg/updater/updater.go

Test no longer copies RWMutex
Removes redundant nil check
/lint

Minor go vet changes

---

cmd/updater/main.go
pkg/summarizer/pubsub.go
pkg/summarizer/summary.go
pkg/updater/BUILD.bazel
pkg/updater/persist.go
pkg/updater/persist_test.go
util/gcs/client.go
util/queue.go

* First try and load the state from GCS
* Thereafter save it to GCS every minute
* Discard any loaded names that are no longer in the queue
* Unit test

Support persisting test group queue across processes.

---

cmd/summarizer/main.go
cmd/updater/main.go
config/BUILD.bazel
config/queue.go
pkg/summarizer/BUILD.bazel
pkg/summarizer/persist.go
pkg/summarizer/summary.go
pkg/updater/BUILD.bazel
pkg/updater/persist.go
util/BUILD.bazel
util/queue/BUILD.bazel
util/queue/persist.go
util/queue/persist_test.go
util/queue/queue.go
util/queue/queue_test.go

* Allow summarizer to accept multiple fixers
* Move util.Queue to util.queue.Queue
* Factor most FixPersistent logic into util.queue package
* Restart summary fixers when the configuration changes.
* Protect summarizer from a dashboard that no longer exists

Add persistent queue to summarizer.

---

config/snapshot/config_snapshot_test.go
pkg/summarizer/summary.go
pkg/updater/BUILD.bazel
pkg/updater/updater.go

- Config Snapshot test now detects if it "does not snapshot when generation match" correctly 
- Deletes unused/duplicate code. This wound up being shockingly little cut, since the "configSnapshot" has already been removed.
/assign @fejta

Config snapshot adjustments

---

metadata/junit/junit.go
metadata/junit/junit_test.go

At Ginkgo v2 the "message" attribute contains the
description from the assert, this change use that attribute to compose
the output of Message function.

junit: Use "message" attribute at Message func

---

util/gcs/local_gcs.go
util/gcs/local_gcs_test.go

The local_gcs library is meant to use a local file store to mock GCS behavior closely. Since GCS allows creating `gs://bucket/very/deeply/nested/files`, so too should the local file version.

Allow local file creation to create nested files

---

cluster/prod/knative/setup-testgrid-pubsub.sh
cluster/prod/knative/summarizer.yaml

Splits the "anything" topic into two: one for test group state and one for tab state
/assign @fejta @chaodaiG 
xref #858

Add pubsub and persistent queue for knative summarizer

---

cluster/prod/knative/summarizer.yaml

Follow-up to https://github.com/GoogleCloudPlatform/testgrid/pull/860
Creates a test summarizer based on tab-state, but does not write results to GCS. Reads from subscription
/assign @fejta

Add tab summarizer to knative

---

cluster/prod/knative/summarizer.yaml
cluster/prod/knative/tabulator.yaml
cluster/prod/summarizer.yaml
cluster/prod/tabulator.yaml

The summarizer now consumes tab data and uses a different subscription

Move the test-group-updates subscription over to the tabulator.

---

pkg/summarizer/BUILD.bazel
pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

The logic to filter down the list of dashboard to those
specified by the `--dashboard` flag has been refactored away.
This adds back the functionality.

Restore --dashboard functionality.

---

pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

Breaking as soon as we find a failure will corrupt the next column's
statuses

Receive all statuses from the column.

---

cmd/tabulator/main.go
pkg/tabulator/BUILD.bazel
pkg/tabulator/tabstate.go
pkg/tabulator/tabstate_test.go

Allows processing to be done between tab states. Actually useful processing to be implemented.
Adds a `copy-only` flag to suppress this behavior.

Add processing to tabulator

---

pkg/tabulator/BUILD.bazel
pkg/tabulator/filter.go
pkg/tabulator/filter_test.go
pkg/tabulator/tabstate.go
pkg/tabulator/tabstate_test.go

Allows the tabulator to use base options to remove entire rows that will be filtered out by the UI and summarizer anyway.
/hold (for further testing)

Add filtering to tabulator

---

cluster/canary/tabulator.yaml

Enabling filtering requires much more memory, since the protos are loaded into memory instead of cloud-copied

Give the canary tabulator updater-like resources

---

cluster/prod/knative/tabulator.yaml
cluster/prod/tabulator.yaml

This reverts commit 0241f4dc03b44c488dd94221de654bbc154d9c3b.
/hold
Do not submit until after https://github.com/GoogleCloudPlatform/testgrid/pull/907 is submitted

Revert "Revert "Filter empty columns in production""

---

cluster/prod/knative/tabulator.yaml
cluster/prod/tabulator.yaml

This reverts commit 6a7fa3b1d15b37d16a46a1b0e3c95cb680788402.
Inflating and deflating the columns (required for this flag) may be deleting alerting data without recalculating it.

Revert "Revert "Revert "Filter empty columns in production"""

---

.gitignore
terraform/Makefile
terraform/README.md
terraform/main.tf
terraform/modules/alerts/main.tf
terraform/modules/alerts/probers.tf
terraform/modules/alerts/variables.tf
terraform/provider.tf

Based on Prow team's work in https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/oss/terraform.

Add basic PubSub alerts using Terraform.

---

pkg/tabulator/BUILD.bazel
pkg/tabulator/tabstate.go
pkg/tabulator/tabstate_test.go

Fixes bug where alerts are missing when the grid is inflated/deflated in the tabulator by recalculating alerts from the available data.
/lint

Set alerts on tabulator while filtering columns

---

cluster/canary/tabulator.yaml

/assign @fejta 
Due to https://github.com/GoogleCloudPlatform/testgrid/issues/617, there isn't effective logic ensuring that the alerting settings are identical between tabs and test groups. This issue should be resolved before `--filter-columns` is rolled out everywhere.
Removing this flag so that the canary signal isn't stuck broken.

Remove filter-columns experiment from canary

---

cmd/tabulator/main.go
pkg/tabulator/tabstate.go
pkg/tabulator/tabstate_test.go

TestGrid isn't universally ready to calculate alerts based only on tab alert settings (see https://github.com/GoogleCloudPlatform/testgrid/issues/617). Put this feature behind a flag so that empty columns can be dropped before needing to make this changeover.

Move tab alert settings behind a flag

---

cluster/canary/tabulator.yaml

Tested on a data snapshot; shown to be setting alert data after running Tabulator with this option.
Reverts https://github.com/GoogleCloudPlatform/testgrid/pull/916

Enable filter-columns on TG Canary

---

pkg/merger/merger.go
pkg/summarizer/summary.go
pkg/tabulator/tabstate.go
pkg/updater/updater.go
util/gcs/gcs.go
util/gcs/local_gcs_test.go
util/gcs/sort.go
util/queue/persist.go

- Fixes a tabulator bug where old cache values can be served to critical service components
- Fixes (presumably) a similar bug with queue persistence files
- Hopefully makes the "no-cache" string a little less magic. It's not intuitive that no-cache does cache, but returns verified cache entries.

Set Tabulator cache settings to "verified cache only"

---

cmd/tabulator/main.go
pkg/tabulator/persist.go
pkg/tabulator/pubsub.go
pkg/tabulator/tabstate.go

Generally seems to run faster at various concurrency levels, while using similar amounts of memory.
/assign @fejta

Refactor tabulator algorithm to tabulate by test group

---

cluster/canary/tabulator.yaml
cluster/prod/knative/tabulator.yaml
cluster/prod/tabulator.yaml

Tabulator takes about 25GiB of memory on first startup, in a burst, and about 10GiB most of the time.
It is using about that much CPU when `--filter-columns` is enabled, though.

Tune tabulator

---

cmd/tabulator/main.go

I don't think this is worth maintaining as a mode of operation

Set filter by regex as default behavior for tabulator

---

pkg/summarizer/BUILD.bazel
pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

Rather than sequentially. Also summarize all tabs for the first dashboard
before starting any of the tabs on a second dashboard.

Concurrently summarize tabs in a dashboard.

---

cluster/canary/tabulator.yaml

Default is true, so the flag does nothing.
Cannot be migrated to prod until https://github.com/GoogleCloudPlatform/testgrid/pull/951 merges.

Remove filter flag from canary

---

cluster/canary/updater.yaml

This will concurrently download builds in test groups, instead
of serially download builds in concurrent test groups.

Turn on pooled updating in canary.

---

internal/result/results.go
internal/result/results_test.go
pkg/summarizer/flakiness.go
pkg/summarizer/flakiness_test.go
pkg/summarizer/summary.go
pkg/summarizer/summary_test.go
pkg/updater/updater.go

Channels are much slower than calling a function
```
1m results:
pkg: github.com/GoogleCloudPlatform/testgrid/internal/result
BenchmarkIterSlow-10            78166888                14.90 ns/op
BenchmarkIterFast-10            759703227                1.559 ns/op
10m results:
pkg: github.com/GoogleCloudPlatform/testgrid/internal/result
BenchmarkIterSlow-10                   1        1360214667 ns/op
BenchmarkIterFast-10            728631373                1.590 ns/op
```

Improve Iter() performance.

---

cmd/summarizer/main.go
pkg/summarizer/pubsub.go

The --tab-path is always filled, so updating the fixer accordingly.
No usage of the --grid-path flag.

Drop --grid-path flag and remaining usage.

---

cluster/prod/tabulator.yaml

Works in canary (https://testgrid.k8s.io/sigtestingmisc#test-infra-fuzz has column stats in canary)

Calculate column stats in prod.

---

cmd/updater/main.go
pkg/updater/updater.go
pkg/updater/updater_test.go

Instead of adding a "Truncated" row to indicate truncated columns, simply cut the columns and replace the last cell in each row with an "unknown" marker.

Truncate testgroup state inline

---

cmd/summarizer/main.go
pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

Adds a flag that allows you to turn off regex filtering (if it's already being done upstream by the tabulator.

Add skip-filter flag for summarizer

---

cluster/canary/summarizer.yaml
cluster/canary/updater.yaml

Enables skipping base options filtering in the summarizer (since that's been done in the tabulator for a while) and inline truncation for the updater.

Enable features in canary

---

cluster/prod/knative/tabulator.yaml
cluster/prod/tabulator.yaml

https://github.com/GoogleCloudPlatform/testgrid/issues/1001 is resolved and alerts appear to be identical across versions
Example:
- https://external-canary-dot-k8s-testgrid.appspot.com/sig-testing-maintenance#ci-janitor
- https://testgrid.k8s.io/sig-testing-maintenance#ci-janitor

Re-enable filter columns in production

---

cluster/prod/knative/summarizer.yaml
cluster/prod/summarizer.yaml

Summarization appears to be identical in dashboards using `base_options`
Compare:
- https://external-canary-dot-k8s-testgrid.appspot.com/sig-storage-kubernetes#Summary
- https://testgrid.k8s.io/sig-storage-kubernetes#Summary

Stop filtering by regex in prod summarizer

---

cmd/summarizer/main.go

Filtering is usually not needed, since this feature has been refactored to the Tabulator.

Switch skip-base-options-filter feature flag to true by default

---

cluster/canary/tabulator.yaml
cluster/prod/knative/tabulator.yaml
cluster/prod/tabulator.yaml

Flag is default on, and is already removed in some builds (ex. canary)

Remove --filter-columns flag

---

cmd/updater/main.go
pb/config/config.proto
pkg/updater/updater.go
pkg/updater/updater_test.go

Since the updater and tabulator will have to agree on how columns are sorted, this is simplified by removing the rarely-used option to customize column sorting.
Due to this extra merge complexity, future column sorting features should probably be implemented in the frontend instead of the backend.

Remove customizable sorting from updater

---

util/gcs/read.go
util/gcs/read_test.go

This extends the junit discovery regex to support bazel's test.xml
naming scheme. With this bazel users do not need to workaround
testgrid's junit_* prefix requirements and can directly run against
bazel-testlogs/ directory's output.

Support bazel format junit files

---

util/metrics/metrics_test.go

Increasing fudge factor, since sometimes this test flakes with a value slightly over 100 milliseconds (e.g. 112 or so). 200 should be plenty.

Reduce flakiness in metrics_test.

---

benchmark/tabulator_bench_test.go
cmd/tabulator/main.go
pkg/tabulator/tabstate.go
pkg/tabulator/tabstate_test.go

`--extend` on the Tabulator will now cause the tabulator to extend state with the information in the updater instead of simply overwriting it.
This feature is most useful for tabs with aggressive filtering: that freed up space can be used now to store more history.

Implement tab state extension

---

pkg/updater/updater.go

- Makes it so that the issues passed into the function don't have the same name as a temporary variable.
- Rename also tries to make it clear what ll. 1031-1039 actually do: deduplicate the array
- Simplifies the SortStarted function signature; the config isn't useful

minor refactors to updater

---

pkg/tabulator/tabstate.go
pkg/tabulator/tabstate_test.go

This change makes the updater (for as long as it cares to update) the absolute authority of the timespan it covers.
Notably, deleted cells (ex: due to a config change) are deleted in the tab as well unless they are older than the updater can remember.

Modify extend-tab feature to patch, not merge

---

cluster/canary/tabulator.yaml

We're currently using a concurrency of 65 reading threads and 128 writing threads. The updater is running with a pool of 10 threads. No need to go so hard!
I suspect the tabulator keeping 65 states inflated and in-memory is why the tabulator is running [out of memory](https://github.com/GoogleCloudPlatform/testgrid/issues/1089) and the updater is _well_ under its request.

Throtle concurrency of tabulator to match updater in canary

---

config/cache.go
config/config.go
pkg/api/v1/BUILD.bazel
pkg/api/v1/config.go
pkg/api/v1/config_cache.go
pkg/api/v1/config_cache_test.go
pkg/api/v1/config_test.go
pkg/api/v1/server.go
pkg/api/v1/state.go

Includes #1086; see second commit for review
Keeps a normalization cache for the API component only. For default configs, increases the normalization cost to constant instead of O(dashboard) or O(dashboard * tabs)
For non-default configs, front-loads the normalization needed without benefit. Keeping multiple cached configs in an expiring cache object in a later PR would improve repeated, non-default calls.

Cache default config as map in API component

---

pkg/api/v1/config.go
pkg/api/v1/config_test.go
pkg/api/v1/server.go
pkg/api/v1/state.go

- same proto imported twice under different aliases
- renamed a proto alias to end with pb
- package comment was defined in several places

fix golint issues

---

pkg/api/BUILD.bazel
pkg/api/router.go
pkg/api/router_http_test.go

Adds a simple "OK" health check when you hit the API with no path.
Allows Ingresses to recognize the API as "healthy"; default health checks will return 200 instead of 404

Add health check to API

---

pkg/api/BUILD.bazel
pkg/api/README.md
pkg/api/router.go
pkg/api/router_http_test.go

Depends on #1103
Makes the "health check" more useful to users, mirroring to simple documentation about the server they've just reached.

Have health check return an API README

---

cmd/updater/main.go
pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read.go
pkg/updater/read_test.go
pkg/updater/updater.go
pkg/updater/updater_test.go

This is flag-guarded so the behavior will not kick in until the flag is set on deployment. Adding this so ignored results properly get excluded when specified in config.

Implement ignore_skip to exclude skipped results.

---

pkg/api/v1/summary.go
pkg/api/v1/summary_test.go

Added `Nanos` to the `timestamp` in `convertSummary` function
Fixes: #1124

Added nanos to timestamp when converting

---

web/custom-elements.json
web/src/tab-summary.ts
web/stories/tab-summary.stories.ts
web/stories/testgrid-index.stories.ts

Added the tab summary component to the existing storybook. Created a separate story for each possible status.
Please refer to the screenshtot

Add a tab summary component and associated stories

---

cmd/README.md
cmd/api/README.md
cmd/config_merger/README.md
cmd/state_comparer/README.md
cmd/summarizer/README.md
cmd/tabulator/README.md
cmd/updater/README.md

I gave these a basic pass that these will run, though if you spot any issues please let me know.
Also cleaned up some old docs from when we were migrating, and tried to make these more consistent (with common tips, etc. in the cmd/ README instead of individual component READMEs).
Ref #1120

Update README files under cmd/ with common tips and commands.

---

pkg/updater/read.go
pkg/updater/read_test.go
pkg/updater/updater.go

Trying to log more info when we hit https://github.com/GoogleCloudPlatform/testgrid/issues/1116. It's unclear what times the Updater is dealing with, so make it clear exactly what it's comparing.

Log more on 'too old' cols when processing started.json

---

go.mod
go.sum
repos.bzl

The `v0.0.9` has a broken dep on a removed GH repo https://github.com/creachadair/staticfile
```
go: github.com/GoogleCloudPlatform/testgrid@v0.0.155 requires
bitbucket.org/creachadair/stringset@v0.0.9 requires
github.com/creachadair/staticfile@v0.1.3: reading github.com/creachadair/staticfile/go.mod at revision v0.1.3: git ls-remote -q origin in /home/afri/Projects/RH/go/pkg/mod/cache/vcs/7f22b487ea423648f3bb75e35ac5adb1ede8f500fbd46b975ca494a23a598447: exit status 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

deps: bump bitbucket.org/creachadair/stringset

---

go.mod
go.sum
pkg/api/BUILD.bazel
pkg/api/router.go
pkg/api/v1/BUILD.bazel
pkg/api/v1/config.go
pkg/api/v1/server.go
pkg/api/v1/state.go
pkg/api/v1/summary.go
repos.bzl

- Gorilla Mux is [archived](https://github.com/gorilla#gorilla-toolkit)
- The only features we're using are URL variables and subrouters, so a lighter-weight library is good, but using the http.ServeMux built-in isn't _quite_ enough.

Move API from Gorilla to Chi

---

pkg/updater/read.go
pkg/updater/read_test.go

Should fix #1116 once released to prod.

Report columns with start = 0 as 'running' so they can update later.

---

web/custom-elements.json
web/index.html
web/package-lock.json
web/package.json
web/src/testgrid-app.ts
web/src/testgrid-index.ts
web/src/testgrid-router.ts
web/src/utils/navigation.ts
web/stories/testgrid-index.stories.ts
web/test/testgrid-index.test.ts
web/web-dev-server.config.mjs

Added the routing capability on top of Ankur's changes.
- Created a `testgrid-app` custom element as a container for router and different views
- Renamed `TestgridIndex` to `testgrid-index` to comply with custom elements naming conventions
- Added a router to render different views based on the pathname
- Changed the web-dev-server config to enable SPA routing
I am currently working on the tests and add them in the next PR

MVP for routing

---

web/src/testgrid-index.ts
web/src/testgrid-router.ts
web/test/testgrid-index.test.ts
web/web-test-runner.config.mjs

fixes #1182 
Improve the existing test cases for `testgrid-index` custom element.
- Remove the `Loading...` entry from the dashboard groups and dashboard properties. This was causing the tests to succeed before correctly rendering with the data from API
- populate a placeholder array instead of pushing into the property array, thus triggering the update multiple items
- Correcting the tests and avoid the flakiness by introducing some timeouts
- Add a test case for checking navigation
- Configure web test runner to have a larger timeout

Improve the tests

---

web/package-lock.json
web/src/dashboard-summary.ts
web/src/testgrid-index.ts
web/src/testgrid-router.ts
web/src/utils/navigation.ts
web/test/dashboard-summary.test.ts
web/test/testgrid-index.test.ts

Getting rid of the buttons to call API and instead do that during the loading/rendering stage - similar to how it's done in the current Testgrid UI.
- Removed call API button from index. Removed the input and button from dashboard summary page.
- Index and dashboard summary content is rendered when the page is loaded.
- Clicking on any dashboard will navigate directly to the dashboard summary page of that dashboard
- Added test for `<dashboard-summary>` component

Render content when the page is loaded

---

web/.storybook/server.mjs
web/custom-elements.json
web/package.json

Running `npm run storybook` for me produces the TestGrid index page, instead of the Storybook UI with all the stories in the sidebar. I believe it's because we're inheriting the app index from the base config; explicitly ignore that for the storybook server.

Fix to show storybook stories instead of app index.

---

web/custom-elements.json
web/package-lock.json
web/package.json
web/src/dashboard-summary.ts
web/test/dashboard-summary.test.ts

Add the tab bar (top of the screenshot) - 
- Added a tab bar with tab names based on mwc components (`mwc-tab` & `mwc-tab-bar`)
- Added the test to make sure tab bar is rendered correctly

Add the tab bar with tab names

---

web/src/tab-summary.ts
web/src/testgrid-dashboard-summary.ts
web/src/testgrid-data-content.ts
web/src/utils/navigation.ts
web/test/testgrid-dashboard-summary.test.ts
web/test/testgrid-data-content.test.ts

Make sure that clicking on tab links doesn't reload the whole page - and more closely resembles the current prod UI.
Also, there was a small bug when going to a tab from summary and going back, the view was not updated properly. this is fixed now

Fix tab links

---

pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

It's possible to have a grid with a column (see https://github.com/GoogleCloudPlatform/testgrid/blob/6ad903765c1a60491ea661d268780aa0e0de71ea/pkg/tabulator/tabstate.go#L445, which keeps a column if the grid would otherwise be empty) but no rows. This is fine, but the stale alert doesn't account for this at the moment. Update it to alert when no rows exist, in addition to the other reasons a tab might be stale.

Alert stale tab when no rows exist.

---

cluster/canary/monitoring.yaml
cluster/prod/monitoring.yaml

Following https://cloud.google.com/stackdriver/docs/solutions/gke/gmp-migration to migrate us to managed prometheus so our metrics work again ^^

Add new pod monitors for metrics on GMP.

---

pkg/updater/resultstore/client.go
pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go

Added the logic to process raw results from Resultstore for easier grouping and conversion into InflatedColumn in the future.
- Added extra fields to fieldmask (actions & configured targets)
- Converted fetched results to singleActionTargetResults (with targetID as a key)
- Set the column Name and Build to invocationID for now
- Added unit tests for processRawResult (which performs the conversion)

Process raw results from Resultstore

---

pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go
pkg/updater/updater.go
pkg/updater/updater_test.go

Added a functionality to apply build override configuration options:
- `build_override_strftime`
- `build_override_configuration_value`
Column's build field will be set according to override configurations.
Added unit tests.

Add build override feature

---

pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go

Extract the group ID based on primary grouping option or fallback to a default grouping by invocation

Extract grouping ID based on configurations

---

pkg/updater/resultstore/BUILD.bazel
pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go

We are just reusing the functionality within updater package, which is already unit tested

Enable custom target result status

---

metadata/junit/junit.go
metadata/junit/junit_test.go

Properties is available for testsuite, not for result in all prow jobs I checked. For now, add properties to Suite only for the safety purpose.
modified:   junit.go
modified:   junit_test.go

Update junit.go to allow more data to be extracted.

---

pkg/summarizer/BUILD.bazel
pkg/summarizer/summary.go
pkg/summarizer/summary_test.go
util/BUILD.bazel
util/links.go
util/links_test.go

The frontend currently processes links, but any components that want to use links (like Summarizer or downstream components) can't really do so. Replicate the logic for link-template parsing so we can make use of the user-specified links instead of hard-coded ones.

Add links for alerts, and utilities to process link templates.

---

config/cache_test.go
config/snapshot/BUILD.bazel
config/snapshot/config_snapshot.go
config/snapshot/config_snapshot_test.go
go.mod
go.sum
pkg/updater/persist_test.go
pkg/updater/read_test.go
pkg/updater/updater_test.go
repos.bzl
util/gcs/fake/fake.go
util/queue/persist_test.go

Adding a quick retry to mitigate issues where the configuration is (temporarily) not available on startup.
Added a unit test for this as well (probably could be cleaner, but it should verify that the retry actually works).
ETA: The actual change to add a retry is in config_snapshot.go. Everything else is an update to add a unit test for the retry, and enhance the storage fake to allow that (with a lock to prevent data races on map reads/writes for the fake Opener).

Add retry when snapshotting configuration.

---

util/gcs/read.go

TestGrid expects that podinfo.json is uploaded by the time that
finished.json is, and will either report it as a running/pending
status if finished.json isn't uploaded yet, or as a failure if it is.
The message that appears on the <job>.Pod cell isn't clear about this
case, so updating the message to include it. (The previous case
mentioned, where Prow's GCS reporter isn't enabled, still applies, but
podinfo.json can fail to be uploaded for other reasons as well).

Clarify message for missing podinfo.json.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

A recent update to Summarizer records column header values (specifically, the 'extra' or 'custom' column header values) when recording metadata about alerted rows. We missed a case where, if there are fewer values recorded than the current number of custom column headers configured for the tab, we hit an out of index issue. (This is a legitimate case that can happen when new custom column headers are added).
Quick-fixed this by checking the length of column header values before recording them, and an additional unit test to verify this case. (We made this change internally, and I've verified it works already).

Fixing a panic when recording column headers in alerts.

---

pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go

Looks like this accidentally reused the logic for the GCS updater, so fixing that. Added unit tests as well.

Fix ResultStore updater to only update relevant groups.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go

It's not expected that podinfo.json is always uploaded from Prow, or that it's an error if it doesn't update. Instead of a neutral status (which affects the tab status in TestGrid), mark this as passing with skips so there's still an informational message, but it doesn't flag the tab as failing or flaky.

Report missing podinfo.json as PASS_WITH_SKIPS.

---

pkg/updater/resultstore/client.go

Forgot to add field masks for fetching configured target stats from ResultStore. Without this, status and timing info don't get fetched when downloading results.

Capture configured target stats from ResultStore.

---

config/BUILD.bazel
config/config.go
config/config_test.go
pkg/updater/resultstore/BUILD.bazel
pkg/updater/resultstore/client.go
pkg/updater/resultstore/query/BUILD.bazel
pkg/updater/resultstore/query/query.go
pkg/updater/resultstore/query/query_test.go
pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go

If searching for a target (as opposed to labels or other identifiers), we want to search for those results using a difference method (SearchConfiguredTargets, rather than SearchInvocations). Add the search method and use it if the query contains a target atom (and update the Prow label accordingly for this search).
Moved the query code into a separate package so it can be used in config validation without a circular dependency.

Use SearchConfiguredTargets when searching targets.

---

util/queue/queue.go
util/queue/queue_test.go

We're hitting an issue occasionally where Tabulator will stall out, which seems to be caused by the queue getting stuck during 'sleep()', likely because the timer channel has already been pulled from in the second select case, and the wait on receiving a value from the timer channel after timer.Stop() fails will block indefinitely.
Instead, ensure that timer.Stop() is definitely called, but don't bother to drain or close the channel. (Note that timer.Stop() doesn't stop the channel, but it should be cleaned up due to being out of scope once sleep() completes).

Fix race on timer in util.queue.

---

cmd/summarizer/main.go
cmd/tabulator/main.go
cmd/updater/main.go

In pubsub v1.32, a breaking change made it so specifying a blank project results in an error, rather than automatically detecting the project as it did before. Instead, specify the sentinel value for detecting the project automatically.
See
https://github.com/googleapis/google-cloud-go/releases/tag/pubsub%2Fv1.32.0.
Note that an update a while back upgraded the pubsub module version from v1.22.2 to v1.33.0.
Verified locally that this change fixes some startup failures that exist on the current images. (This should be fixed the next time images are built and the autobump includes them in configs).

Specify auto-project detection for PubSub.

---

cluster/canary/updater.yaml
cluster/prod/updater.yaml
cluster/setup-pubsub.sh
cluster/setup-testgrid-pubsub.sh

Includes two changes:
- Add a canary and prod subscription on gs://kubernetes-ci-logs to the PubSub setup script. (And run it so the new subscriptions are registered on k8s-testgrid. This should eventually get replaced with Terraform setup, but that's probably better to do later if/when we migrate to a separate setup for Kubernetes).
- Add the subscriptions to the Updater config, so the Updater responds to updates on gs://kubernetes-ci-logs (same as it does for gs://kubernetes-jenkins).
Ref https://github.com/kubernetes/test-infra/issues/33386
(That will be fixed once these changes make it to prod).

Subscribe to gs://kubernetes-ci-logs updates.

---

cmd/state_comparer/main.go
cmd/state_comparer/main_test.go
config/BUILD.bazel
config/config.go
config/config_test.go
config/converge.go
config/fields_test.go
config/yamlcfg/BUILD.bazel
config/yamlcfg/yaml2proto.go
config/yamlcfg/yaml2proto_test.go
pkg/summarizer/summary_test.go
pkg/updater/eval.go
pkg/updater/gcs_test.go
pkg/updater/inflate_test.go
pkg/updater/read_test.go
pkg/updater/updater.go
pkg/updater/updater_test.go

This should fix most of the lint errors in the repo. I'm ignoring a few files that don't get touched often or don't have obvious fixes (mainly around imports).

Fix Golang lint errors.
