GoogleCloudPlatform/testgrid

.bazelrc
cluster/BUILD.bazel
cluster/entomologist_deployment.yaml
cluster/setup.sh
hack/print-workspace-status.sh

Points current canary build cluster to k8s-testgrid
Puts build in "testgrid" namespace, even though cluster is dedicated for
now

Change Build Cluster Settings

---

go.mod
go.sum

Resubmit to retrigger testing (see #9)

Fixing go.mod module path.

---

cmd/summarizer/example/BUILD.bazel
cmd/summarizer/example/client.go
cmd/summarizer/example/fake_response.go

Fixing imports in summarizer.

---

cmd/summarizer/BUILD.bazel
cmd/summarizer/main.go
cmd/summarizer/main_test.go

Add unit tests for:
* TestUpdateDashboard (basic)
* TestUpdateTab (basic)
* TestReadGrid
Refactor some code to better encapsulate away some GCS complexity for
easier unit testing.

TestUpdateDashboard TestUpdateTab TestReadGrid

---

config/yamlcfg/yaml2proto.go

/assign @fejta @chases2 
Edit: See https://github.com/kubernetes/test-infra/issues/15294 for context/tracking.

Actually reconcile ignore_skip in default.yaml.

---

cmd/summarizer/main.go
cmd/summarizer/main_test.go

Let me know if you'd prefer me to break this up into multiple PRs.

Unit tests for all functionality

---

cmd/summarizer/main.go
cmd/summarizer/main_test.go

Specifies the number of passing columns and cells.
/hold
ref #52

Create summary status message

---

cluster/summarizer_deployment.yaml
cluster/updater_deployment.yaml
cmd/summarizer/main.go
cmd/updater/main.go

* Use service account in summarizer, updater
* Update immediately the first time

Allow reading from beta subdir

---

cmd/updater/main.go

Including an ETA on when it should complete

Log progress every minute

---

cmd/summarizer/main.go

This will allow us to load this by passsing `?summary=beta` to app engine

Write summary to summary-foo instead of dashboard-foo

---

README.md
build_test_update.md

Also fixed a couple other links to test-infra code.
fixes #74

Fix link for configuration docs.

---

resultstore/resultstore.go

Add the properties field for the Target struct to match the resultstore's Target proto.

Add the properties field for the Target struct

---

cluster/summarizer_deployment.yaml
cluster/updater_deployment.yaml

Working on automating this:
#77 #78

Update testgrid to v0.0.1-alpha.4

---

resultstore/resultstore.go
resultstore/resultstore_test.go

Add unit test for the Target struct since we added the Properties attribute for the test Target and we are expecting to use the Target struct in the resultstore.

Add unit test for the fromTarget function

---

cluster/deploy.sh

Conveniently this should also test running the script!

Correct deploy.sh documentation

---

pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

Fix some lint errors

---

config/BUILD.bazel
config/config.go
config/config_test.go
go.mod
go.sum
repos.bzl

Add some universal validation of the config proto to TestGrid.
Will be following up with more validation in a follow-up PR.

Validate TestGrid config uses unique names.

---

pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

Also stop assuming an extra column exists, even when processing a kubernetes client.
/assign @michelle192837 @chases2

Support summarizing non kubernetes clients.

---

config/config.go
config/config_test.go
config/yamlcfg/yaml2proto_test.go

Validate current incorrect column header behavior (will correct tomorrow).
/assign @michelle192837 @chases2 
ref https://github.com/kubernetes/test-infra/issues/16625

Validate things are balanced and not empty.

---

resultstore/BUILD.bazel
resultstore/client.go
resultstore/client_test.go
resultstore/resultstore.go

Adding Search function to upstream TestGrid resultstore. Adding context as an argument to allow others to call the function and pass in their own context.

Adding Search function to the resultstore client.

---

resultstore/README.md

Adding instruction and code snippet on invocation search.

Add README for the resultstore client

---

cluster/canary/updater.yaml
cluster/prod/updater.yaml

Also fix canary updater location

Update prod updater to 20200714, turn off confirm.

---

pkg/summarizer/flakiness.go
pkg/summarizer/flakiness_test.go

Ultimately makes Summarizer summaries with healthiness analysis much smaller.

Change Healthiness report to filter out test methods

---

pkg/updater/BUILD.bazel
pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/updater.go

Unit test this behavior.
Will soon refactor updater.go to work with this instead of the current structure.

Convert a GCS result into an inflatedColumn.

---

pkg/updater/updater.go
util/gcs/BUILD.bazel
util/gcs/read.go
util/gcs/read_test.go

Suites() coverage

---

util/gcs/BUILD.bazel
util/gcs/read_test.go

Test coverage for Started() and Finished()

---

util/gcs/read.go
util/gcs/read_test.go

Rename interrogator to client

---

cmd/updater/main.go
pkg/updater/updater.go
util/gcs/read.go
util/gcs/read_test.go

Also sort slices instead of a custom type.

Refactor gcs client out of Build

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Add test coverage for appendColumn, appendCell, appendMetric

Refactor updater to use inflatedColumn.

---

pkg/updater/BUILD.bazel
pkg/updater/read.go
pkg/updater/updater.go
pkg/updater/updater_test.go
util/gcs/read_test.go

Add constructGrid and testGroupPath

---

cmd/updater/main.go
config/config.go
pkg/summarizer/summary.go
pkg/updater/BUILD.bazel
pkg/updater/inflate.go
pkg/updater/read.go
pkg/updater/updater.go
pkg/updater/updater_test.go
util/gcs/BUILD.bazel
util/gcs/client.go

Otherwise use downloaded grid data for older columns.

Only reprocess last 4 hours of results

---

pkg/updater/read.go
pkg/updater/read_test.go

ref https://github.com/GoogleCloudPlatform/testgrid/issues/184

Fix race condition when multiple go-routines reach an old build

---

cluster/prod/summarizer.yaml
cluster/prod/updater.yaml
pkg/updater/updater.go

Also drop Advanced stop message to debug for next release

 Promote v20200804-v0.0.15-29-g09b67a9 to prod

---

cluster/prod/updater.yaml

Matches https://github.com/GoogleCloudPlatform/testgrid/blob/8f1a867064d4bec75c4a8e790120bffebf8e360a/cluster/canary/updater.yaml#L27

Correct --config flag

---

cmd/updater/BUILD.bazel
cmd/updater/main.go
cmd/updater/main_test.go

Allow unit test this apparently problematic code

Allow k8s-testgrid when gridPrefix is filled.

---

util/gcs/read.go
util/gcs/read_test.go

Instead of
> `groupConcurrency * buildConcurrency * len(junit_suites)`
Reduce this to
> `groupConcurrency * buildConcurrency * min(5, len(junit_suites))`
This will mitigate the chance of running out of memory while still affording lots of parallelism.
ref https://github.com/GoogleCloudPlatform/testgrid/issues/194

Limit the number of concurrent junit downloads in a single build.

---

cluster/prod/summarizer.yaml
cluster/prod/updater.yaml

Promote v20200806-v0.0.16-12-g054d30c to prod

---

cluster/canary/summarizer.yaml
cluster/canary/updater.yaml

Upgrade canary to v20200807-v0.0.17-8-gd205182

---

cluster/prod/summarizer.yaml
cluster/prod/updater.yaml

Promote v20200807-v0.0.17-8-gd205182 to prod

---

OWNERS

Also simplify yaml file by removing redundant reviewers section (remove Cole in the process)
/assign @e-blackwelder

Add Ethan to approvers.

---

WORKSPACE
cluster/canary/summarizer.yaml

Also fixup some summarizer deployment fields.

Update to rules_k8s v0.5

---

cluster/prod/summarizer.yaml

This one will use the `&grid=beta` result state to compute its summaries

Add a beta summarizer to prod

---

cluster/prod/summarizer.yaml

https://oss-prow.knative.dev/view/gs/oss-prow/logs/post-testgrid-deploy-prod/1296204625321398272#1:build-log.txt%3A36

Dedup summarizer names

---

metadata/junit/BUILD.bazel
metadata/junit/junit.go
metadata/junit/junit_test.go

Also add some test coverage junit.Parse
fixes #220

Parse empty junit files as an empty Suites.

---

pkg/summarizer/flakiness.go
pkg/summarizer/flakiness_test.go

Add logic to the flakiness calculation to exclude columns that are consistently failing.  This prevents our flakiness metric from increasing across the board during failures that affect every test.

Add a column filter to flakiness algorithm

---

cluster/prod/summarizer.yaml
cluster/prod/updater.yaml

Promote v20200911-v0.0.21-2-gffa64bc to prod

---

cmd/updater/main.go
cmd/updater/main_test.go

Less updater concurrency by default

---

cluster/canary/updater.yaml
cluster/prod/updater.yaml

Also increase update frequency
ref https://github.com/GoogleCloudPlatform/testgrid/issues/236

Increase updater timeouts.

---

build_test_update.md

To avoid anyone digging to long when attempting to make UI changes I thought I would make a more direct reference to the status.  
/cc eddiezane #245

Add more prominent information about UI changes

---

cluster/prod/summarizer.yaml
cluster/prod/updater.yaml

Fixes https://github.com/GoogleCloudPlatform/testgrid/issues/236

Promote v20201015-v0.0.25-2-g481a3cb to prod

---

util/gcs/read.go
util/gcs/read_test.go

Also:
* Do not duplicate `gs://` when printing paths (this is already part of the build path's URL scheme)
* Add unit test coverage for this scenario
* Make unit tests more robust (the linking fake was cheating a bit too much)
ref https://github.com/GoogleCloudPlatform/testgrid/issues/236

Handle GCS prefix returning earlier builds

---

cluster/canary/summarizer.yaml
cluster/canary/updater.yaml

ref https://github.com/GoogleCloudPlatform/testgrid/issues/236

Upgrade canary to v20201020-v0.0.25-8-g957c387

---

cluster/prod/summarizer.yaml
cluster/prod/updater.yaml

Fixes https://github.com/GoogleCloudPlatform/testgrid/issues/236

Promote v20201020-v0.0.25-8-g957c387 to prod

---

cmd/updater/README.md

Link to state proto

---

cmd/updater/main.go
pkg/updater/updater.go
pkg/updater/updater_test.go

Also fix `Update()` to put `ctx` first.

Only process kubernetes client groups.

---

internal/result/results.go

Make results Lte and Gte not stutter.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Add unit test coverage.
/assign @chaodaiG

Handle gcs.ResolveReference() errors.

---

cmd/updater/main.go
pkg/updater/BUILD.bazel
pkg/updater/updater.go
pkg/updater/updater_test.go

Intent is to allow private updaters more control over the update process.

Refactor update to allow control over updateGroup.

---

internal/result/BUILD.bazel
internal/result/results.go
internal/result/results_test.go

BUILD_PASSED should be a passing result.
Coalesce should consider anything not passing (and not a special case) a failure.

Fix IsPassingResult() and Coalesce().

---

WORKSPACE
config/yamlcfg/BUILD.bazel
config/yamlcfg/yaml2proto.go
config/yamlcfg/yaml2proto_test.go

(This is going in a separate branch to facilitate local testing and for experimentation).

Allow local defaults for a config directory.

---

util/gcs/read.go
util/gcs/read_test.go

ref https://github.com/kubernetes/test-infra/issues/19696 https://github.com/GoogleCloudPlatform/testgrid/issues/211

Find link in either link or x-goog-meta-link header

---

cluster/canary/summarizer.yaml
cluster/canary/updater.yaml

Includes an update order mitigation

Push v20201207-v0.0.32-7-ge8106ca to canary.

---

cluster/canary/summarizer.yaml
cluster/canary/updater.yaml

Fix for updater race condition
/assign @chaodaiG

Update canary to v20201210-v0.0.33-4-g3dc75e8.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Sets a ceiling of the number of cells updated per loop, which should minimize memory pressure.

Maximize the number of updated cells

---

pkg/updater/updater.go

Currently happening once per column per update

Only alert rows once per update.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read.go

In some scenarios we appear to spend significant amount of time creating a unique test name.
Add a context to this function and detect when this context deadline has expired so this function
does not take an excessive amount of time.
Also log whenever 100 rows have the same disambiguated name

Add context to convertResult.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go

Excessive numbers of similarly named cells harms performance, so drop these additional rows with an injected notice row

Limit the number of rows with the exact same rendered name.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

ref https://github.com/GoogleCloudPlatform/testgrid/issues/312

Remove rows that no longer appear on the grid

---

metadata/junit/junit.go
metadata/junit/junit_test.go
util/gcs/read_test.go

ref https://github.com/kubernetes/test-infra/issues/20335

Handle empty junit suites correctly

---

pkg/updater/inflate_test.go

Fix unit test error message

---

cmd/summarizer/main.go

Deduplicate context declaration in Summarizer

---

standalone.md

Remove trailing whitespace

---

pkg/updater/gcs.go
pkg/updater/read.go
pkg/updater/read_test.go

/assign @chases2 
Does this make the behavior any clearer?

Move row rendering logic inside nameConfig

---

config/yamlcfg/yaml2proto.go
config/yamlcfg/yaml2proto_test.go

...to prevent people from uploading configs that have incorrect fields and don't do anything. For example: default_test_group in a non default file.

Change config to reject invalid fields for yaml

---

pkg/updater/inflate.go
pkg/updater/inflate_test.go

Only read cell_id from filled columns

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Follow up to https://github.com/GoogleCloudPlatform/testgrid/pull/365; set this info in the Updater too.
(renamed a few things for clarity).

Add latest cell and build ID to failures.

---

util/gcs/read.go
util/gcs/read_test.go

Hack listing to handle sequential build numbers

---

pkg/updater/inflate.go
pkg/updater/updater.go
pkg/updater/updater_test.go

* Add metrics regardless of the cell result
* Send the column index to appendCell, as metrics' spare-encoding needs this.

Append metrics correctly.

---

pkg/updater/gcs_test.go

Test analyzeProwJob explicitly

---

hack/BUILD.bazel
hack/compare_states.go
hack/compare_states_test.go
pkg/updater/read.go
pkg/updater/updater.go
pkg/updater/updater_test.go
util/gcs/BUILD.bazel
util/gcs/gcs.go
util/gcs/local_gcs.go

This is not intended to compare two states in detail, but is a quick check that two states are pretty reasonably close by comparing rows and columns of each. (Also provides a diff of the rows and columns as it works).
This goes into hack/ as a possible helper script if you're making changes to Updater or something similar, and want to check states are not drastically wrong.

Add quick script to compare two TestGrid states.

---

config/config.go
config/config_test.go

Fixes https://github.com/GoogleCloudPlatform/testgrid/issues/98
- Tests added to check for empty dashboards and return an error in that case
- Tests added to check for a short entity length: 0-2 length entities are not valid

Validate dashboard name length and dashboardTab length

---

cluster/canary/config_merger.yaml
cluster/prod/config_merger.yaml

Pins all config mergers to the current version

Update Config Merger SA

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go

Currently merging both passes and failures will always result in a flaky status.
Externally this is the correct behavior for junit prow results. However other
result systems need the ability to fail these types of results so add this ability.
Also take the highest filled message rather than the first non-empty one.

Allow MergeCells to fail results with passes.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go

These are now exported functions. Also choose a better name for enabling a flaky status.

Document MergeCells and SplitCells.

---

cluster/prod/knative/summarizer.yaml
cluster/prod/knative/updater.yaml

Use json logs on knative shard

---

pkg/updater/updater.go
pkg/updater/updater_test.go

This options results in a group of column only using the most recent result for a given row.
By default there will be a row, row [1], row [2], etc. When this option is on we will instead
just take the most recent cell and put it into row, dropping the other cells.

Implement ignore_old_results.

---

util/gcs/BUILD.bazel
util/gcs/read.go
util/gcs/sort.go
util/gcs/sort_test.go

Correctly document and add unit test

Move Sort() into sort.go.

---

pkg/updater/read.go
pkg/updater/read_test.go

Columns can now be sorted in any order, so make a pass through all columns to extract
this information.

Stop assuming the largest hint and start time is the first column.

---

pkg/summarizer/BUILD.bazel
pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

/assign @michelle192837 
ref https://github.com/GoogleCloudPlatform/testgrid/issues/453

Set summarized path correctly

---

pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

Currently we will consider num_columns_recent filled columns for each row. For sparse grids this
can result in an amusing side effect where all recent columns pass while the overall status
remains flaky. This is because a row may have failures in its num_columns_recent non-empty cells,
but if the empty cells are at the front, these failures may be outside the tab's num_columns_recent.
Fix this by stopping as soon as we find num_columns_recent columns with at least one filled cell.
Columns with running rows do not count toward num_columns_recent.
ref https://github.com/GoogleCloudPlatform/testgrid/issues/461

Stop flaky/pass overall status after num_columns_recent filled columns.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Currently we reprocess all results that completed within the last 12 hours.
This wastes resources and causes undesirable side effects:
- Continually download the same data for 12 hours
- Large grids may get truncated and only partially process the last 12 hours
This results in testgrid appearing up to 12 hours stale
We do this because there's a race between uploading the finished.json and
junit files getting uploaded (these are done in parallel). Other systems
can have similiar types of races.
We now mitigate against this by reprocessing all columns at least as recent
as the oldest running column, and we correctly distinguish between running
and completed jobs. So this is no longer necessary.
We protect against jobs stuck running by timing them out after 72 hours.
/cc @michelle192837

Reduce reprocessing time.

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/inflate.go
pkg/updater/inflate_test.go
pkg/updater/read.go
pkg/updater/updater.go
pkg/updater/updater_test.go

Honor this config value and pull from junit properties.
Add to inflated Cell
ref #472

Add support for user_property field.

---

pkg/summarizer/summary.go

/cc @chases2 
I am concerned with doing this sort of thing, because people tend to be more fluent in English than golang. Thus minds prefer reading the English. But only the golang determines how the program actually behaves. We need people maintaining this code to read the golang.

Add some documentation to overallStatus()

---

BUILD.bazel
config/print/README.md

Allow go programs to access local filesystems through Bazel

---

hack/compare_states.go
util/gcs/gcs.go

Lint fixes

---

config/config.go
config/config_test.go
config/print/main.go
config/yamlcfg/yaml2proto.go
metadata/job.go
pkg/updater/gcs.go
resultstore/resultstore.go
util/gcs/fake/fake.go
util/gcs/gcs.go
util/metrics/log.go

Fix lint issues in the repo.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Export ConstructGrid.

---

config/print/main.go

To run:
`bazel run //config/print:print -- -path=/tmp/testgrid-states/config -print-field-use=true`

Optionally print all config fields and # of uses.

---

pb/README.md

An explanation for how TestGrid stores data in general, with some common debugging commands.

Add Protocol Buffer Readme

---

config/queue.go

Changes to the queue should end sleeps early

---

cmd/summarizer/main.go
cmd/updater/main.go
pkg/updater/updater_test.go
util/metrics/BUILD.bazel
util/metrics/log.go
util/metrics/log_test.go
util/metrics/metrics.go

Change Val to Values() and make it specific to logging metrics.
Create a reporter which only logs metric values periodically

Refactor metrics interface.

---

cmd/config_merger/main.go
cmd/summarizer/main.go
cmd/updater/main.go
pkg/updater/BUILD.bazel
pkg/updater/updater_test.go
util/metrics/log.go
util/metrics/log_test.go

This makes it easy to track their existence and print them regularly

Refactor logging metrics into a struct.

---

config/print/main.go

Pretty-print config by default

---

cmd/api/main.go
pkg/api/router.go
pkg/api/v1/config.go
pkg/api/v1/config_test.go

"bad copying" == "Don't copy locks" and "Don't copy big protos"
/assign @fejta 
/lint

Fix linting and bad copying in api package

---

config/queue.go

Log when we add/remove/update when we want to update a group

---

pkg/updater/read.go
pkg/updater/read_test.go

Initially the updater aborted the test group when it encountered a problematic build.
Next it would just ignore the column.
Today it emits a synthetic column that gives information about what parts of the build
are problematic.
This obviates the need to have readColumns() return an error indicating whether or not it found
any error-free columns.
Today so long as 1 column is free of errors we return a nil error (even if 9 others have problems).
This changes it so that we'll also return nil error it that last column also contains an error.
Since we always return a nil error, remove this from the function signature.

Synthetic columns are not readColumns errors.

---

pkg/updater/updater.go

Instead of retrying every half period, retry between a quarter and half period.
This reduces the chance of retrying many errors at the same time.
Also add some additional trace logging

Add a random duration before retrying errors.

---

pkg/updater/read_test.go
pkg/updater/updater_test.go
util/gcs/fake/fake.go
util/gcs/read_test.go

--runs_per_test=100 shows no failures
Fixes #500

Deflake unit tests.

---

config/config.go
config/config_test.go

Fixing up a few bugs I noticed while evaluating another config yesterday:
- tabular_name_regex is counting subexpressions wrong due to how regexp.SubexpNames() works
- short text should be > not >= and count runes (5 emoji is fine to display), not characters
- an empty gcs_prefix is valid if result_source is specified

Fix a few bugs in config validation.

---

pkg/updater/updater.go

We want to allocate half the time to reading new columns and the second half to compiling them.
This fixes this by calculating the time to read new columns at the beginning of the function instead
of after many long operations (downloading old grid, reading first new column).
Currently the effect is more allocate half the time remaining after reading the first column to reading additional columns
and the second half to uploading. This generally works but not in some edge cases where it takes a long
time to get the first column.

Allocate half the time to compile and upload results.

---

cluster/canary/summarizer.yaml
cluster/prod/summarizer.yaml
cmd/summarizer/main.go

Drop unneeded beta-summarizer, doing this work instead by normal summarizer.
Also specify some resource requests/limits.

Modernize summarizer deployment.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

When grids exceeds 10MB of compressed data start dropping row data.
If that doesn't work then start merging columns together.

Shrink grids to a reasonable size.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Also if we do shrink, cut down to half the max size so we do not wind up shrinking every cycle.

Limit the amount of time spent shrinking.

---

pkg/updater/updater.go

Otherwise when update frequency is less than timeout we can have multiple routines updating the same group

Track groups that are updating.

---

cluster/canary/api.yaml

Also pins API to version to be updated with other canary services

Move API canary to GKE Ingress

---

config/queue.go
config/queue_test.go
pkg/updater/updater.go

Use this in the updater to generally only reduce the next time.
Also correctly detect when Stat() fails because the object does not exist.

Allow only reducing the time for a queued item.

---

cluster/canary/updater.yaml

Add manual subscriptions to canary.

---

cluster/prod/updater.yaml

Also sort flags and update resource config to better match what autopilot is adjusting it to
/cc @chaodaiG  @cjwagner

Add --subscribe flags to prod.

---

cluster/create-subscription.sh
cluster/create-topic.sh
cluster/setup-pubsub.sh

Also update create-topic to handle a single prefix per notification configuration

Update setup-pubsub.sh for mulitple topics.

---

cluster/prod/knative/summarizer.yaml

Remove deprecated beta-summarizer from knative

---

cmd/api/main.go
pkg/api/router.go
pkg/api/v1/BUILD.bazel
pkg/api/v1/config_test.go
pkg/api/v1/server.go
pkg/api/v1/state.go
pkg/api/v1/state_test.go

Add implementation for ListHeaders, ListRows
* /dashboards/{dashboard}/tabs/{tab}/headers -> ListHeaders
* /dashboards/{dashboard}/tabs/{tab}/rows -> ListRows

Add implementation for ListHeaders, ListRows

---

pkg/updater/updater.go
pkg/updater/updater_test.go

This generally only happens when running locally (otherwise freq/--wait is set to something reasonable), and only when there's an error in the update, but it is annoying when it happens.

Fix a panic in updater (if update errors and freq = 0)

---

go.mod
go.sum
hack/BUILD.bazel
hack/compare_states.go
hack/compare_states_test.go
repos.bzl

Follow-ups after this:
- Incorporate @chaodaiG's parallelization for grabbing files (which makes sense) and ensure this is usable with GCS, not just local files (https://github.com/chaodaiG/testgrid/commit/311cc1522c041d635bce17f1dff7e31d88642962)
- Promote this out of hack/ to cmd/

Add more options for comparing states.

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Check the correct stat error.

---

cluster/prod/knative/OWNERS
cluster/prod/knative/setup-pubsub.sh
cluster/prod/knative/updater.yaml

Configure pubsub for knative testgrid instance

---

cluster/canary/updater.yaml
cluster/prod/updater.yaml

ref https://github.com/kubernetes/test-infra/issues/23720

Increase CPU, RAM and --build-concurrency

---

cluster/canary/updater.yaml

* More/Higher
- group concurrency
- group timeout
- cpu
- ram
* Less build concurrency

Tune canary concurrency, timeout, ram, cpu

---

cluster/prod/updater.yaml

Tune prod updater.

---

pkg/updater/inflate.go
pkg/updater/inflate_test.go

Refactor inflation to use callback iteration rather than channels

---

pkg/updater/BUILD.bazel
pkg/updater/inflate_test.go

Run with: `go test ./pkg/updater -bench=.`
https://pkg.go.dev/testing#hdr-Benchmarks

Add BenchmarkInflateGrid

---

pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

xref https://github.com/GoogleCloudPlatform/testgrid/issues/683

Fix latest run timestamp assignment

---

pkg/updater/updater.go
pkg/updater/updater_test.go

This helps correctly track the first time a failure happens when passes-to-close > 1 and a row is alternating between fails and passes.

Don't consider an alert started until there are enough passes.

---

cluster/canary/config_merger.yaml
cluster/canary/monitoring.yaml
cluster/prod/config_merger.yaml
cluster/prod/monitoring.yaml

Step 2 of https://github.com/GoogleCloudPlatform/testgrid/issues/744

Add Pod Monitors to Config Merger

---

cluster/canary/monitoring.yaml
cluster/canary/summarizer.yaml
cluster/canary/updater.yaml
cluster/prod/monitoring.yaml
cluster/prod/summarizer.yaml
cluster/prod/updater.yaml
cmd/summarizer/BUILD.bazel
cmd/summarizer/main.go
cmd/updater/BUILD.bazel
cmd/updater/main.go

Convert all controllers to emit prometheus metrics

---

cluster/prod/config_merger.yaml
cluster/prod/knative/summarizer.yaml
cluster/prod/knative/updater.yaml
cluster/prod/summarizer.yaml
cluster/prod/updater.yaml

This reverts commit e70e12e1fe370558c4fe5f1a17af2d759580660a.

Revert "Bumping Testgrid Prod"

---

util/metrics/prometheus/prometheus.go

Make prometheus metrics safe for concurrency

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Right now if the first column to merge has fewer headers than subsequent ones, the updater will panic

Support merging columns with more/fewer column headers.

---

util/metrics/prometheus/prometheus_test.go

Confirmed locally that race-detection tests pass with https://github.com/GoogleCloudPlatform/testgrid/pull/750 and fail without it.
/cc @fejta

Add concurrence-safety tests to prometheus metrics

---

pkg/summarizer/summary.go

If 3 tabs get new results at the same time, we only want to update the summary
once, not three times concurrently. So only allow one workers to actively update
a dashboard. However, if a tab is updated while the dashboard is getting updated
then it is likely already stale, so we want to wait for this dashboard to complete
and immediately queue up a new run once it finishes.

Prevent concurrently updating the same dashboard.

---

pkg/merger/BUILD.bazel
pkg/merger/merger.go
pkg/updater/updater.go

Also fixes linting error in updater

Use Factory in metric generation for config_merger

---

pkg/summarizer/summary.go

Stop logging the raw proto.
Start logging important a few important stats about the proto instead.

Improve summarizer logging.

---

config.md

Added documentation entry about new prow job annotation added here: https://github.com/kubernetes/test-infra/pull/24731

Add testgrid-base-options to config.md

---

config/snapshot/BUILD.bazel
config/snapshot/config_snapshot_test.go
go.mod

ref: comment in https://github.com/GoogleCloudPlatform/testgrid/pull/785
/assign @fejta

Deduplicate context dependency

---

config/snapshot/config_snapshot.go
pkg/summarizer/BUILD.bazel
pkg/summarizer/summary.go

Marginally increases test coverage in this package (56.9% -> 60.7%)

Move summarizer to config snapshot library

---

pb/config/config.pb.go
pb/config/config.proto
pkg/updater/gcs.go
pkg/updater/gcs_test.go
pkg/updater/read.go

Allows a junit property to set a user-specified icon on the cell.

Support test annotations.

---

cluster/canary/updater.yaml
cluster/prod/updater.yaml

* Also add .json suffix to the json file

Enable persistent queue for prod

---

pkg/summarizer/persist.go
pkg/summarizer/summary.go
util/queue/persist.go

* More relevant logging
* Ensure queue is initialized
* Reset fix context when config changes

Improve persistent summarizer queue

---

config/snapshot/BUILD.bazel
config/snapshot/config_snapshot.go
config/snapshot/config_snapshot_test.go
pkg/summarizer/summary.go
pkg/tabulator/BUILD.bazel
pkg/tabulator/tabstate.go

Refactor config snapshot to use channels

---

util/queue/persist.go

Allow a grace period after the context expires for GCS operations to complete.
Log less noisily if the context was canceled

Improve persistent queue routine.

---

cluster/prod/knative/summarizer.yaml
cluster/prod/summarizer.yaml

Enable persistent summarizer queue in prod

---

cluster/prod/BUILD.bazel
cluster/prod/tabulator.yaml
util/gcs/local_gcs.go

/hold
(Apparently includes a small GCS change because some is weird with my branch -.-. That said, I think this is a fine change)

Add Tabulator to prod.

---

cluster/prod/README.md

Bare bones, but think this covers what we want to do in most cases.

Add basic instructions for adding a new component to the release.

---

cluster/canary/summarizer.yaml

Remove canary test-group summarizer

---

cluster/prod/knative/summarizer.yaml
cluster/prod/summarizer.yaml

Use tab-based summaries in production

---

cluster/canary/tabulator.yaml

Persist the canary tabulator queue

---

cmd/tabulator/BUILD.bazel
cmd/tabulator/main.go
pkg/tabulator/tabstate.go

Add a repeatable flag that allows the tabulator to operate on only a few dashboards

Add --dashboard flag to tabulator

---

cluster/canary/updater.yaml
cluster/prod/updater.yaml

Reprocess some prod groups on change.

---

cluster/prod/updater.yaml

Reprocess all prod groups on change

---

cmd/tabulator/main.go
pkg/tabulator/BUILD.bazel
pkg/tabulator/tabstate.go
pkg/tabulator/tabstate_test.go
pkg/updater/updater.go
pkg/updater/updater_test.go

Drop empty columns after filtering by regex

---

cluster/prod/knative/tabulator.yaml
cluster/prod/tabulator.yaml

Add filtering to tabulator production

---

cluster/prod/knative/tabulator.yaml
cluster/prod/tabulator.yaml

This reverts commit 065d2a0864ae7a6fd951533e8b754c4c57812122.

Revert "Filter empty columns in production"

---

pkg/tabulator/tabstate.go
pkg/tabulator/tabstate_test.go

Refactor only. Brings test_status import more in line with similar imports in the updater

Alias test_status protobuf

---

pkg/tabulator/tabstate.go

Inflating the grid uses a lot of resources on big instances. Moving the inflateGrid call behind the flag that requires it.

Move inflate behind flag

---

pkg/updater/updater.go
pkg/updater/updater_test.go

Refactor ConstructGrid to use needed arguments instead of the entire testgroup config
Will be used to construct a grid and set alerts in the Tabulator with a mixture of testgroup and dashboard tab settings. Will delete redundant test in a later PR (not done here to ensure no functional change that would fail tests).

Refactor ConstructGrid

---

benchmark/tabulator.sh

This is the script I used to gather data on https://github.com/GoogleCloudPlatform/testgrid/pull/942

Add benchmark script

---

pkg/summarizer/summary.go

If we get interrupted summarizing tabs we should try to continue at the next available opportunity.
/hold

Track when a dashboard needs more tabs summarized

---

.gitignore
BUILD.bazel
benchmark/BUILD.bazel
benchmark/tabulator.sh
benchmark/tabulator_bench_test.go

follow-up to https://github.com/GoogleCloudPlatform/testgrid/pull/943
/assign @fejta

Use go for tabulator benchmarking

---

cluster/canary/tabulator.yaml
cluster/prod/knative/tabulator.yaml
cluster/prod/tabulator.yaml

This makes the logs easier to work with

Use --json-logs on kubernetes.

---

cluster/prod/knative/tabulator.yaml
cluster/prod/tabulator.yaml

follow-up to https://github.com/GoogleCloudPlatform/testgrid/pull/954

Remove filter flag from production

---

benchmark/tabulator_bench_test.go
cmd/tabulator/main.go
pkg/tabulator/BUILD.bazel
pkg/tabulator/tabstate.go

Drop copyOnly support for tabulator

---

internal/result/results_test.go

Also create the iter inside the benchmark loop (otherwise we just time the first one)
```
pkg: github.com/GoogleCloudPlatform/testgrid/internal/result
BenchmarkIter/few_chan-10         	       8	 133878224 ns/op
BenchmarkIter/few_func-10         	     531	   2243046 ns/op
BenchmarkIter/many_chan-10        	       1	1345504917 ns/op
BenchmarkIter/many_func-10        	      52	  22549506 ns/op
```

Refactor benchmark to be table driven.

---

.gitignore
benchmark/tabulator_bench_test.go
cmd/tabulator/main.go
pkg/tabulator/BUILD.bazel
pkg/tabulator/tabstate.go
pkg/tabulator/tabstate_test.go

Follow-up to https://github.com/GoogleCloudPlatform/testgrid/pull/942

Refactor Tabulator to read and write in separate pools

---

benchmark/tabulator.sh
pkg/tabulator/tabstate.go
pkg/tabulator/tabstate_test.go

Adds tests that will catch unexpectedly-nil configs
Addresses #1001

Fix test group config in task creation in tabulator

---

.bazelrc

follow https://github.com/bazelbuild/bazel-toolchains/blob/master/bazelrc/bazel-4.1.0.bazelrc

modernize .bazelrc

---

cluster/canary/updater.yaml
cluster/prod/knative/updater.yaml
cluster/prod/updater.yaml

Flag is default true (and slated for removal)

Remove --skip-inline flag from cluster

---

cluster/canary/summarizer.yaml
cluster/prod/knative/summarizer.yaml
cluster/prod/summarizer.yaml

Remove --skip-base-options-filter flag

---

cmd/tabulator/main.go

This is set true everywhere now.

Flip --column-stats true by default.

---

cmd/summarizer/main.go
pkg/summarizer/summary.go
pkg/summarizer/summary_test.go

Filtering has been migrated to the tabulator

Remove summarizer-side filtering

---

pkg/updater/gcs.go
pkg/updater/gcs_test.go

fix: https://github.com/kubernetes/kubernetes/issues/111510
Signed-off-by: Dave Chen <dave.jungler@gmail.com>
@BenTheElder @aojea @pohly

fix: Add skipped status back for Ginkgo v2

---

config/config.go

Fixed the golint issue with variable naming

---

cmd/api/README.md
cmd/api/main.go
pkg/api/BUILD.bazel
pkg/api/router.go

Also adds a small readme to explain usage and basic testing

Add gRPC support to API

---

config/snapshot/config_snapshot.go
config/snapshot/config_snapshot_test.go
pkg/api/v1/BUILD.bazel
pkg/api/v1/config.go
pkg/api/v1/config_http_test.go
pkg/api/v1/server.go
pkg/api/v1/state.go
pkg/api/v1/state_http_test.go

Refactoring to prepare for https://github.com/GoogleCloudPlatform/testgrid/issues/1075 and for more intelligent caching of the default scope in general.

Refactor API to get config snapshot

---

cluster/prod/tabulator.yaml

Throttle tabulator to 10 concurrent states

---

CONTRIBUTING.md
standalone.md

Minor clarifications for standalone instructions.

---

go.mod
go.sum
repos.bzl

Basically #1125 but running update-deps to satisfy presubmits.

Update client_golang from 1.11.0 to 1.11.1.

---

benchmark/tabulator_bench_test.go
cmd/summarizer/main.go
cmd/tabulator/main.go
cmd/updater/main.go
pkg/summarizer/summary.go
pkg/tabulator/tabstate.go
pkg/updater/updater.go
pkg/updater/updater_test.go

move parameters to struct

---

cmd/api/main.go
cmd/summarizer/main.go
pkg/api/router.go
pkg/api/v1/server.go
pkg/api/v1/server_fake.go
pkg/api/v1/state.go
pkg/api/v1/state_test.go

Updated the path prefixes according to the new flow: `Updater > Tabulator (turn a grid into the user-viewed grid) > Summarizer`
Fixes: #1123

Updated path prefixes

---

pkg/api/v1/summary_test.go

Fix go vet issues

---

cluster/deploy.sh

Fixed gcp warnings

---

pkg/api/README.md
pkg/api/v1/server.go
pkg/api/v1/summary.go
pkg/api/v1/summary_test.go

- Added HTTP endpoints for dashboard level summaries
- Added tests for HTTP endpoints
- Updated the API documentation with the new endpoints

Add HTTP endpoints

---

web/rollup.config.js

This follows the example outlined on https://www.npmjs.com/package/@rollup/plugin-terser.

Fix the terser plugin import.

---

.prow.yaml
web/package-lock.json
web/package.json

Kinda jank, but this does successfully run the presubmits.
Forces running on Playwright and uses one of their available images (see https://playwright.dev/docs/ci).
Fixes #1178
/hold

Add npm presubmit job.

---

web/src/testgrid-dashboard-summary.ts
web/src/testgrid-data-content.ts
web/src/testgrid-grid-display.ts
web/src/testgrid-index.ts
web/src/utils/constants.ts
web/web-dev-server.config.mjs
web/web-test-runner.config.mjs

Lets us use different API URLs for dev, test, prod in the future

Configure API host as env variables.

---

web/custom-elements.json
web/src/fake-api/data.json
web/src/fake-api/routes.json
web/src/testgrid-dashboard-summary.ts
web/src/testgrid-group-summary.ts
web/stories/testgrid-group-summary.stories.ts
web/test/testgrid-group-summary.test.ts

Added a group summary element as in the screenshot - 
Added the element, story and tests.
The element is not embedded in the code

Add a group summary element, stories and tests

---

pkg/updater/BUILD.bazel
pkg/updater/resultstore/BUILD.bazel
pkg/updater/resultstore/client.go
pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go
resultstore/resultstore.go
resultstore/resultstore_test.go

Initial commit that adds some logic and basic unit tests for these functions.
Will follow up with further changes once I verify this works against a real API.

Add ResultStore search to Updater.

---

pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go

Added the functionality to group the results based on the group ID in #1242.
Added unit tests for the functionality above.
Renamed some variables for better clarity

Group invocations according to grouping strategy

---

pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go

Process invocation groups - aka convert each group into its own InflatedColumn.
Invocation groups were created in #1246 
Added unit tests.

Process groups instead of individual invocations

---

pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go

Headers can be extracted from both invocations as well as single action target results

add functionality to extract custom headers

---

pkg/updater/gcs.go
pkg/updater/resultstore/BUILD.bazel
pkg/updater/resultstore/resultstore.go
pkg/updater/resultstore/resultstore_test.go

Finishing up Sultan's PR: #1253

Add cell metrics to resultstore

---

go.mod
go.sum
pkg/merger/BUILD.bazel
pkg/merger/merger.go
repos.bzl

Fixes: https://github.com/kubernetes/test-infra/issues/33971

Use sigs.k8s.io/yaml/goyaml.v3

---

README.md

Closes https://github.com/kubernetes-sigs/testgrid/issues/2

Add info on frontends to README.md
